/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetAuthEmailConfirmationParams,
  PostAuthChangePasswordBody,
  PostAuthForgotPassword200,
  PostAuthForgotPasswordBody,
  PostAuthLocalBody,
  PostAuthLocalRegisterBody,
  PostAuthResetPasswordBody,
  PostAuthSendEmailConfirmation200,
  PostAuthSendEmailConfirmationBody,
  UsersPermissionsUserRegistration
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getConnectProviderResponse301 = {
  data: void
  status: 301
}

export type getConnectProviderResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 301>
}

;
export type getConnectProviderResponseError = (getConnectProviderResponse301 | getConnectProviderResponseDefault) & {
  headers: Headers;
};

export type getConnectProviderResponse = (getConnectProviderResponseError)

export const getGetConnectProviderUrl = (provider: string,) => {




  return `/connect/${provider}`
}

/**
 * Redirects to provider login before being redirect to /auth/{provider}/callback
 * @summary Login with a provider
 */
export const getConnectProvider = async (provider: string, options?: Parameters<typeof strapiFetch>[1]): Promise<getConnectProviderResponse> => {

  return strapiFetch<getConnectProviderResponse>(getGetConnectProviderUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConnectProviderQueryKey = (provider: string,) => {
    return [
    `/connect/${provider}`
    ] as const;
    }


export const getGetConnectProviderQueryOptions = <TData = Awaited<ReturnType<typeof getConnectProvider>>, TError = void | Error>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConnectProviderQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConnectProvider>>> = ({ signal }) => getConnectProvider(provider, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConnectProviderQueryResult = NonNullable<Awaited<ReturnType<typeof getConnectProvider>>>
export type GetConnectProviderQueryError = void | Error


export function useGetConnectProvider<TData = Awaited<ReturnType<typeof getConnectProvider>>, TError = void | Error>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectProvider>>,
          TError,
          Awaited<ReturnType<typeof getConnectProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConnectProvider<TData = Awaited<ReturnType<typeof getConnectProvider>>, TError = void | Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConnectProvider>>,
          TError,
          Awaited<ReturnType<typeof getConnectProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConnectProvider<TData = Awaited<ReturnType<typeof getConnectProvider>>, TError = void | Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login with a provider
 */

export function useGetConnectProvider<TData = Awaited<ReturnType<typeof getConnectProvider>>, TError = void | Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConnectProvider>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConnectProviderQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postAuthLocalResponse200 = {
  data: UsersPermissionsUserRegistration
  status: 200
}

export type postAuthLocalResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthLocalResponseSuccess = (postAuthLocalResponse200) & {
  headers: Headers;
};
export type postAuthLocalResponseError = (postAuthLocalResponseDefault) & {
  headers: Headers;
};

export type postAuthLocalResponse = (postAuthLocalResponseSuccess | postAuthLocalResponseError)

export const getPostAuthLocalUrl = () => {




  return `/auth/local`
}

/**
 * Returns a jwt token and user info
 * @summary Local login
 */
export const postAuthLocal = async (postAuthLocalBody: PostAuthLocalBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthLocalResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthLocalResponse>(getPostAuthLocalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthLocalBody)
  }
);}





export const getPostAuthLocalMutationKey = () => ['postAuthLocal'] as const;

export const getPostAuthLocalMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLocal>>, TError,PostAuthLocalMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLocal>>, TError,PostAuthLocalMutationVariables, TContext> => {

const mutationKey = getPostAuthLocalMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLocal>>, PostAuthLocalMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthLocal(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLocalMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLocal>>>
    export type PostAuthLocalMutationBody = PostAuthLocalBody
    export type PostAuthLocalMutationError = Error
    export type PostAuthLocalMutationVariables = {data: PostAuthLocalBody}

    /**
 * @summary Local login
 */
export const usePostAuthLocal = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLocal>>, TError,PostAuthLocalMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLocal>>,
        TError,
        PostAuthLocalMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthLocalMutationOptions(options), queryClient);
    }
    export type postAuthLocalRegisterResponse200 = {
  data: UsersPermissionsUserRegistration
  status: 200
}

export type postAuthLocalRegisterResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthLocalRegisterResponseSuccess = (postAuthLocalRegisterResponse200) & {
  headers: Headers;
};
export type postAuthLocalRegisterResponseError = (postAuthLocalRegisterResponseDefault) & {
  headers: Headers;
};

export type postAuthLocalRegisterResponse = (postAuthLocalRegisterResponseSuccess | postAuthLocalRegisterResponseError)

export const getPostAuthLocalRegisterUrl = () => {




  return `/auth/local/register`
}

/**
 * Returns a jwt token and user info
 * @summary Register a user
 */
export const postAuthLocalRegister = async (postAuthLocalRegisterBody: PostAuthLocalRegisterBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthLocalRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthLocalRegisterResponse>(getPostAuthLocalRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthLocalRegisterBody)
  }
);}





export const getPostAuthLocalRegisterMutationKey = () => ['postAuthLocalRegister'] as const;

export const getPostAuthLocalRegisterMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLocalRegister>>, TError,PostAuthLocalRegisterMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLocalRegister>>, TError,PostAuthLocalRegisterMutationVariables, TContext> => {

const mutationKey = getPostAuthLocalRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLocalRegister>>, PostAuthLocalRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthLocalRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLocalRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLocalRegister>>>
    export type PostAuthLocalRegisterMutationBody = PostAuthLocalRegisterBody
    export type PostAuthLocalRegisterMutationError = Error
    export type PostAuthLocalRegisterMutationVariables = {data: PostAuthLocalRegisterBody}

    /**
 * @summary Register a user
 */
export const usePostAuthLocalRegister = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLocalRegister>>, TError,PostAuthLocalRegisterMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLocalRegister>>,
        TError,
        PostAuthLocalRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthLocalRegisterMutationOptions(options), queryClient);
    }
    export type getAuthProviderCallbackResponse200 = {
  data: UsersPermissionsUserRegistration
  status: 200
}

export type getAuthProviderCallbackResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type getAuthProviderCallbackResponseSuccess = (getAuthProviderCallbackResponse200) & {
  headers: Headers;
};
export type getAuthProviderCallbackResponseError = (getAuthProviderCallbackResponseDefault) & {
  headers: Headers;
};

export type getAuthProviderCallbackResponse = (getAuthProviderCallbackResponseSuccess | getAuthProviderCallbackResponseError)

export const getGetAuthProviderCallbackUrl = (provider: string,) => {




  return `/auth/${provider}/callback`
}

/**
 * @summary Default Callback from provider auth
 */
export const getAuthProviderCallback = async (provider: string, options?: Parameters<typeof strapiFetch>[1]): Promise<getAuthProviderCallbackResponse> => {

  return strapiFetch<getAuthProviderCallbackResponse>(getGetAuthProviderCallbackUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthProviderCallbackQueryKey = (provider: string,) => {
    return [
    `/auth/${provider}/callback`
    ] as const;
    }


export const getGetAuthProviderCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getAuthProviderCallback>>, TError = Error>(provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthProviderCallbackQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProviderCallback>>> = ({ signal }) => getAuthProviderCallback(provider, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: provider !== null && provider !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthProviderCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthProviderCallback>>>
export type GetAuthProviderCallbackQueryError = Error


export function useGetAuthProviderCallback<TData = Awaited<ReturnType<typeof getAuthProviderCallback>>, TError = Error>(
 provider: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProviderCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthProviderCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthProviderCallback<TData = Awaited<ReturnType<typeof getAuthProviderCallback>>, TError = Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProviderCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthProviderCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthProviderCallback<TData = Awaited<ReturnType<typeof getAuthProviderCallback>>, TError = Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Default Callback from provider auth
 */

export function useGetAuthProviderCallback<TData = Awaited<ReturnType<typeof getAuthProviderCallback>>, TError = Error>(
 provider: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthProviderCallback>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthProviderCallbackQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postAuthForgotPasswordResponse200 = {
  data: PostAuthForgotPassword200
  status: 200
}

export type postAuthForgotPasswordResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthForgotPasswordResponseSuccess = (postAuthForgotPasswordResponse200) & {
  headers: Headers;
};
export type postAuthForgotPasswordResponseError = (postAuthForgotPasswordResponseDefault) & {
  headers: Headers;
};

export type postAuthForgotPasswordResponse = (postAuthForgotPasswordResponseSuccess | postAuthForgotPasswordResponseError)

export const getPostAuthForgotPasswordUrl = () => {




  return `/auth/forgot-password`
}

/**
 * @summary Send rest password email
 */
export const postAuthForgotPassword = async (postAuthForgotPasswordBody: PostAuthForgotPasswordBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthForgotPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthForgotPasswordResponse>(getPostAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthForgotPasswordBody)
  }
);}





export const getPostAuthForgotPasswordMutationKey = () => ['postAuthForgotPassword'] as const;

export const getPostAuthForgotPasswordMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,PostAuthForgotPasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,PostAuthForgotPasswordMutationVariables, TContext> => {

const mutationKey = getPostAuthForgotPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthForgotPassword>>, PostAuthForgotPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthForgotPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthForgotPassword>>>
    export type PostAuthForgotPasswordMutationBody = PostAuthForgotPasswordBody
    export type PostAuthForgotPasswordMutationError = Error
    export type PostAuthForgotPasswordMutationVariables = {data: PostAuthForgotPasswordBody}

    /**
 * @summary Send rest password email
 */
export const usePostAuthForgotPassword = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,PostAuthForgotPasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthForgotPassword>>,
        TError,
        PostAuthForgotPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthForgotPasswordMutationOptions(options), queryClient);
    }
    export type postAuthResetPasswordResponse200 = {
  data: UsersPermissionsUserRegistration
  status: 200
}

export type postAuthResetPasswordResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthResetPasswordResponseSuccess = (postAuthResetPasswordResponse200) & {
  headers: Headers;
};
export type postAuthResetPasswordResponseError = (postAuthResetPasswordResponseDefault) & {
  headers: Headers;
};

export type postAuthResetPasswordResponse = (postAuthResetPasswordResponseSuccess | postAuthResetPasswordResponseError)

export const getPostAuthResetPasswordUrl = () => {




  return `/auth/reset-password`
}

/**
 * @summary Rest user password
 */
export const postAuthResetPassword = async (postAuthResetPasswordBody: PostAuthResetPasswordBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthResetPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthResetPasswordResponse>(getPostAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthResetPasswordBody)
  }
);}





export const getPostAuthResetPasswordMutationKey = () => ['postAuthResetPassword'] as const;

export const getPostAuthResetPasswordMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,PostAuthResetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,PostAuthResetPasswordMutationVariables, TContext> => {

const mutationKey = getPostAuthResetPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResetPassword>>, PostAuthResetPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResetPassword>>>
    export type PostAuthResetPasswordMutationBody = PostAuthResetPasswordBody
    export type PostAuthResetPasswordMutationError = Error
    export type PostAuthResetPasswordMutationVariables = {data: PostAuthResetPasswordBody}

    /**
 * @summary Rest user password
 */
export const usePostAuthResetPassword = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,PostAuthResetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResetPassword>>,
        TError,
        PostAuthResetPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthResetPasswordMutationOptions(options), queryClient);
    }
    export type postAuthChangePasswordResponse200 = {
  data: UsersPermissionsUserRegistration
  status: 200
}

export type postAuthChangePasswordResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthChangePasswordResponseSuccess = (postAuthChangePasswordResponse200) & {
  headers: Headers;
};
export type postAuthChangePasswordResponseError = (postAuthChangePasswordResponseDefault) & {
  headers: Headers;
};

export type postAuthChangePasswordResponse = (postAuthChangePasswordResponseSuccess | postAuthChangePasswordResponseError)

export const getPostAuthChangePasswordUrl = () => {




  return `/auth/change-password`
}

/**
 * @summary Update user's own password
 */
export const postAuthChangePassword = async (postAuthChangePasswordBody: PostAuthChangePasswordBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthChangePasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthChangePasswordResponse>(getPostAuthChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthChangePasswordBody)
  }
);}





export const getPostAuthChangePasswordMutationKey = () => ['postAuthChangePassword'] as const;

export const getPostAuthChangePasswordMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext> => {

const mutationKey = getPostAuthChangePasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthChangePassword>>, PostAuthChangePasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthChangePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthChangePassword>>>
    export type PostAuthChangePasswordMutationBody = PostAuthChangePasswordBody
    export type PostAuthChangePasswordMutationError = Error
    export type PostAuthChangePasswordMutationVariables = {data: PostAuthChangePasswordBody}

    /**
 * @summary Update user's own password
 */
export const usePostAuthChangePassword = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthChangePassword>>,
        TError,
        PostAuthChangePasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthChangePasswordMutationOptions(options), queryClient);
    }
    export type getAuthEmailConfirmationResponse301 = {
  data: void
  status: 301
}

export type getAuthEmailConfirmationResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 301>
}

;
export type getAuthEmailConfirmationResponseError = (getAuthEmailConfirmationResponse301 | getAuthEmailConfirmationResponseDefault) & {
  headers: Headers;
};

export type getAuthEmailConfirmationResponse = (getAuthEmailConfirmationResponseError)

export const getGetAuthEmailConfirmationUrl = (params?: GetAuthEmailConfirmationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/email-confirmation?${stringifiedParams}` : `/auth/email-confirmation`
}

/**
 * @summary Confirm user email
 */
export const getAuthEmailConfirmation = async (params?: GetAuthEmailConfirmationParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getAuthEmailConfirmationResponse> => {

  return strapiFetch<getAuthEmailConfirmationResponse>(getGetAuthEmailConfirmationUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthEmailConfirmationQueryKey = (params?: GetAuthEmailConfirmationParams,) => {
    return [
    `/auth/email-confirmation`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthEmailConfirmationQueryOptions = <TData = Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError = void | Error>(params?: GetAuthEmailConfirmationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthEmailConfirmationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthEmailConfirmation>>> = ({ signal }) => getAuthEmailConfirmation(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthEmailConfirmationQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthEmailConfirmation>>>
export type GetAuthEmailConfirmationQueryError = void | Error


export function useGetAuthEmailConfirmation<TData = Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError = void | Error>(
 params: undefined |  GetAuthEmailConfirmationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthEmailConfirmation>>,
          TError,
          Awaited<ReturnType<typeof getAuthEmailConfirmation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthEmailConfirmation<TData = Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError = void | Error>(
 params?: GetAuthEmailConfirmationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthEmailConfirmation>>,
          TError,
          Awaited<ReturnType<typeof getAuthEmailConfirmation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthEmailConfirmation<TData = Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError = void | Error>(
 params?: GetAuthEmailConfirmationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Confirm user email
 */

export function useGetAuthEmailConfirmation<TData = Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError = void | Error>(
 params?: GetAuthEmailConfirmationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthEmailConfirmation>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthEmailConfirmationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postAuthSendEmailConfirmationResponse200 = {
  data: PostAuthSendEmailConfirmation200
  status: 200
}

export type postAuthSendEmailConfirmationResponseDefault = {
  data: Error
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthSendEmailConfirmationResponseSuccess = (postAuthSendEmailConfirmationResponse200) & {
  headers: Headers;
};
export type postAuthSendEmailConfirmationResponseError = (postAuthSendEmailConfirmationResponseDefault) & {
  headers: Headers;
};

export type postAuthSendEmailConfirmationResponse = (postAuthSendEmailConfirmationResponseSuccess | postAuthSendEmailConfirmationResponseError)

export const getPostAuthSendEmailConfirmationUrl = () => {




  return `/auth/send-email-confirmation`
}

/**
 * @summary Send confirmation email
 */
export const postAuthSendEmailConfirmation = async (postAuthSendEmailConfirmationBody: PostAuthSendEmailConfirmationBody, options?: Parameters<typeof strapiFetch>[1]): Promise<postAuthSendEmailConfirmationResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postAuthSendEmailConfirmationResponse>(getPostAuthSendEmailConfirmationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthSendEmailConfirmationBody)
  }
);}





export const getPostAuthSendEmailConfirmationMutationKey = () => ['postAuthSendEmailConfirmation'] as const;

export const getPostAuthSendEmailConfirmationMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>, TError,PostAuthSendEmailConfirmationMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>, TError,PostAuthSendEmailConfirmationMutationVariables, TContext> => {

const mutationKey = getPostAuthSendEmailConfirmationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>, PostAuthSendEmailConfirmationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthSendEmailConfirmation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSendEmailConfirmationMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>>
    export type PostAuthSendEmailConfirmationMutationBody = PostAuthSendEmailConfirmationBody
    export type PostAuthSendEmailConfirmationMutationError = Error
    export type PostAuthSendEmailConfirmationMutationVariables = {data: PostAuthSendEmailConfirmationBody}

    /**
 * @summary Send confirmation email
 */
export const usePostAuthSendEmailConfirmation = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>, TError,PostAuthSendEmailConfirmationMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSendEmailConfirmation>>,
        TError,
        PostAuthSendEmailConfirmationMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthSendEmailConfirmationMutationOptions(options), queryClient);
    }
