/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { About } from './about';
import type { AboutResponseMeta } from './aboutResponseMeta';

export interface AboutResponse {
  data?: About;
  meta?: AboutResponseMeta;
}
