/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type AboutRequestData = {
  description?: string;
  cover?: number | string;
  title: string;
  summary?: string;
  locale?: string;
  localizations?: (number | string)[];
};
