/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type AboutListResponseMetaPagination = {
  page?: number;
  /** @minimum 25 */
  pageSize?: number;
  /** @maximum 1 */
  pageCount?: number;
  total?: number;
};
