/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { AboutCoverCreatedBy } from './aboutCoverCreatedBy';
import type { AboutCoverFolder } from './aboutCoverFolder';
import type { AboutCoverLocalizationsItem } from './aboutCoverLocalizationsItem';
import type { AboutCoverRelatedItem } from './aboutCoverRelatedItem';
import type { AboutCoverUpdatedBy } from './aboutCoverUpdatedBy';

export type AboutCover = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: AboutCoverRelatedItem[];
  folder?: AboutCoverFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: AboutCoverCreatedBy;
  updatedBy?: AboutCoverUpdatedBy;
  locale?: string;
  localizations?: AboutCoverLocalizationsItem[];
};
