/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { AboutRequestData } from './aboutRequestData';

export interface AboutRequest {
  data: AboutRequestData;
}
