/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { AboutCover } from './aboutCover';
import type { AboutCreatedBy } from './aboutCreatedBy';
import type { AboutUpdatedBy } from './aboutUpdatedBy';

export interface About {
  id?: string | number;
  documentId?: string;
  description?: string;
  cover?: AboutCover;
  title: string;
  summary?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: AboutCreatedBy;
  updatedBy?: AboutUpdatedBy;
  locale?: string;
  localizations?: About[];
}
