/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { About } from './about';
import type { AboutListResponseMeta } from './aboutListResponseMeta';

export interface AboutListResponse {
  data?: About[];
  meta?: AboutListResponseMeta;
}
