/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { AboutListResponseMetaPagination } from './aboutListResponseMetaPagination';

export type AboutListResponseMeta = {
  pagination?: AboutListResponseMetaPagination;
};
