/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Contact } from './contact';
import type { ContactListResponseMeta } from './contactListResponseMeta';

export interface ContactListResponse {
  data?: Contact[];
  meta?: ContactListResponseMeta;
}
