/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ContactListResponseMetaPagination } from './contactListResponseMetaPagination';

export type ContactListResponseMeta = {
  pagination?: ContactListResponseMetaPagination;
};
