/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type ContactRequestData = {
  title?: string;
  summary?: string;
  cover?: number | string;
  description?: string;
  phone?: string;
  email?: string;
  locale?: string;
  localizations?: (number | string)[];
};
