/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type ContactCoverLocalizationsItem = {
  id?: string | number;
  documentId?: string;
};
