/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Contact } from './contact';
import type { ContactResponseMeta } from './contactResponseMeta';

export interface ContactResponse {
  data?: Contact;
  meta?: ContactResponseMeta;
}
