/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ContactRequestData } from './contactRequestData';

export interface ContactRequest {
  data: ContactRequestData;
}
