/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ContactCoverCreatedBy } from './contactCoverCreatedBy';
import type { ContactCoverFolder } from './contactCoverFolder';
import type { ContactCoverLocalizationsItem } from './contactCoverLocalizationsItem';
import type { ContactCoverRelatedItem } from './contactCoverRelatedItem';
import type { ContactCoverUpdatedBy } from './contactCoverUpdatedBy';

export type ContactCover = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ContactCoverRelatedItem[];
  folder?: ContactCoverFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ContactCoverCreatedBy;
  updatedBy?: ContactCoverUpdatedBy;
  locale?: string;
  localizations?: ContactCoverLocalizationsItem[];
};
