/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ContactCover } from './contactCover';
import type { ContactCreatedBy } from './contactCreatedBy';
import type { ContactUpdatedBy } from './contactUpdatedBy';

export interface Contact {
  id?: string | number;
  documentId?: string;
  title?: string;
  summary?: string;
  cover?: ContactCover;
  description?: string;
  phone?: string;
  email?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ContactCreatedBy;
  updatedBy?: ContactUpdatedBy;
  locale?: string;
  localizations?: Contact[];
}
