/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type DeleteUsersPermissionsRolesRole200Ok = typeof DeleteUsersPermissionsRolesRole200Ok[keyof typeof DeleteUsersPermissionsRolesRole200Ok];


export const DeleteUsersPermissionsRolesRole200Ok = {
  true: true,
} as const;
