/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteUsersPermissionsRolesRole200Ok } from './deleteUsersPermissionsRolesRole200Ok';

export type DeleteUsersPermissionsRolesRole200 = {
  ok?: DeleteUsersPermissionsRolesRole200Ok;
};
