/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorErrorDetails } from './errorErrorDetails';

export type ErrorError = {
  status?: number;
  name?: string;
  message?: string;
  details?: ErrorErrorDetails;
};
