/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { EventFlyerCreatedBy } from './eventFlyerCreatedBy';
import type { EventFlyerFolder } from './eventFlyerFolder';
import type { EventFlyerLocalizationsItem } from './eventFlyerLocalizationsItem';
import type { EventFlyerRelatedItem } from './eventFlyerRelatedItem';
import type { EventFlyerUpdatedBy } from './eventFlyerUpdatedBy';

export type EventFlyer = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: EventFlyerRelatedItem[];
  folder?: EventFlyerFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: EventFlyerCreatedBy;
  updatedBy?: EventFlyerUpdatedBy;
  locale?: string;
  localizations?: EventFlyerLocalizationsItem[];
};
