/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { EventCoverCreatedBy } from './eventCoverCreatedBy';
import type { EventCoverFolder } from './eventCoverFolder';
import type { EventCoverLocalizationsItem } from './eventCoverLocalizationsItem';
import type { EventCoverRelatedItem } from './eventCoverRelatedItem';
import type { EventCoverUpdatedBy } from './eventCoverUpdatedBy';

export type EventCover = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: EventCoverRelatedItem[];
  folder?: EventCoverFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: EventCoverCreatedBy;
  updatedBy?: EventCoverUpdatedBy;
  locale?: string;
  localizations?: EventCoverLocalizationsItem[];
};
