/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Event } from './event';
import type { EventListResponseMeta } from './eventListResponseMeta';

export interface EventListResponse {
  data?: Event[];
  meta?: EventListResponseMeta;
}
