/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { EventRequestData } from './eventRequestData';

export interface EventRequest {
  data: EventRequestData;
}
