/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type EventRequestDataEventType = typeof EventRequestDataEventType[keyof typeof EventRequestDataEventType];


export const EventRequestDataEventType = {
  'stages-et-retraites': 'stages-et-retraites',
  'cours-reguliers': 'cours-reguliers',
  'programmes-et-cycles': 'programmes-et-cycles',
} as const;
