/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { EventListResponseMetaPagination } from './eventListResponseMetaPagination';

export type EventListResponseMeta = {
  pagination?: EventListResponseMetaPagination;
};
