/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type EventRequestDataUniverse = typeof EventRequestDataUniverse[keyof typeof EventRequestDataUniverse];


export const EventRequestDataUniverse = {
  yoga: 'yoga',
  mindfulness: 'mindfulness',
  dialogue: 'dialogue',
} as const;
