/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { EventRequestDataEventType } from './eventRequestDataEventType';
import type { EventRequestDataUniverse } from './eventRequestDataUniverse';

export type EventRequestData = {
  title: string;
  summary?: string;
  cover: number | string;
  universe?: EventRequestDataUniverse;
  description: string;
  startAt: string;
  endAt: string;
  flyer?: number | string;
  slug: string;
  displayTitle?: string;
  location?: string;
  organizers?: string;
  online: boolean;
  facebookLink?: string;
  programmes?: (number | string)[];
  eventType: EventRequestDataEventType;
  locale?: string;
  localizations?: (number | string)[];
};
