/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRole } from './usersPermissionsRole';

export type GetUsersPermissionsRoles200RolesItem = UsersPermissionsRole & {
  nb_users?: number;
};
