/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersPermissionsRoles200RolesItem } from './getUsersPermissionsRoles200RolesItem';

export type GetUsersPermissionsRoles200 = {
  roles?: GetUsersPermissionsRoles200RolesItem[];
};
