/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionsTree } from './usersPermissionsPermissionsTree';

export type GetUsersPermissionsPermissions200 = {
  permissions?: UsersPermissionsPermissionsTree;
};
