/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HomeCreatedBy } from './homeCreatedBy';
import type { HomeUpdatedBy } from './homeUpdatedBy';

export interface Home {
  id?: string | number;
  documentId?: string;
  introduction?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: HomeCreatedBy;
  updatedBy?: HomeUpdatedBy;
  locale?: string;
  localizations?: Home[];
}
