/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HomeRequestData } from './homeRequestData';

export interface HomeRequest {
  data: HomeRequestData;
}
