/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Home } from './home';
import type { HomeResponseMeta } from './homeResponseMeta';

export interface HomeResponse {
  data?: Home;
  meta?: HomeResponseMeta;
}
