/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { HomeListResponseMetaPagination } from './homeListResponseMetaPagination';

export type HomeListResponseMeta = {
  pagination?: HomeListResponseMetaPagination;
};
