/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type HomeRequestData = {
  introduction?: string;
  locale?: string;
  localizations?: (number | string)[];
};
