/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PageListResponseMetaPagination } from './pageListResponseMetaPagination';

export type PageListResponseMeta = {
  pagination?: PageListResponseMetaPagination;
};
