/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PageCover } from './pageCover';
import type { PageCreatedBy } from './pageCreatedBy';
import type { PageUpdatedBy } from './pageUpdatedBy';
import type { Programme } from './programme';

export interface Page {
  id?: string | number;
  documentId?: string;
  programmes?: Programme[];
  title: string;
  summary?: string;
  introduction?: string;
  cover?: PageCover;
  slug: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: PageCreatedBy;
  updatedBy?: PageUpdatedBy;
  locale?: string;
  localizations?: Page[];
}
