/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PageRequestData = {
  programmes?: (number | string)[];
  title: string;
  summary?: string;
  introduction?: string;
  cover?: number | string;
  slug: string;
  locale?: string;
  localizations?: (number | string)[];
};
