/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PageRequestData } from './pageRequestData';

export interface PageRequest {
  data: PageRequestData;
}
