/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PageCoverCreatedBy } from './pageCoverCreatedBy';
import type { PageCoverFolder } from './pageCoverFolder';
import type { PageCoverLocalizationsItem } from './pageCoverLocalizationsItem';
import type { PageCoverRelatedItem } from './pageCoverRelatedItem';
import type { PageCoverUpdatedBy } from './pageCoverUpdatedBy';

export type PageCover = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: PageCoverRelatedItem[];
  folder?: PageCoverFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: PageCoverCreatedBy;
  updatedBy?: PageCoverUpdatedBy;
  locale?: string;
  localizations?: PageCoverLocalizationsItem[];
};
