/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Page } from './page';
import type { PageListResponseMeta } from './pageListResponseMeta';

export interface PageListResponse {
  data?: Page[];
  meta?: PageListResponseMeta;
}
