/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthChangePasswordBody = {
  password: string;
  currentPassword: string;
  passwordConfirmation: string;
};
