/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsersPermissionsRoles200Ok } from './postUsersPermissionsRoles200Ok';

export type PostUsersPermissionsRoles200 = {
  ok?: PostUsersPermissionsRoles200Ok;
};
