/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersPermissionsRoles200Ok = typeof PostUsersPermissionsRoles200Ok[keyof typeof PostUsersPermissionsRoles200Ok];


export const PostUsersPermissionsRoles200Ok = {
  true: true,
} as const;
