/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthLocalRegisterBody = {
  username?: string;
  email?: string;
  password?: string;
};
