/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthSendEmailConfirmation200Sent = typeof PostAuthSendEmailConfirmation200Sent[keyof typeof PostAuthSendEmailConfirmation200Sent];


export const PostAuthSendEmailConfirmation200Sent = {
  true: true,
} as const;
