/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsRole } from './usersPermissionsRole';
import type { UsersPermissionsUser } from './usersPermissionsUser';

export type PostUsers201 = UsersPermissionsUser & {
  role?: UsersPermissionsRole;
};
