/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthForgotPassword200Ok } from './postAuthForgotPassword200Ok';

export type PostAuthForgotPassword200 = {
  ok?: PostAuthForgotPassword200Ok;
};
