/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthSendEmailConfirmation200Sent } from './postAuthSendEmailConfirmation200Sent';

export type PostAuthSendEmailConfirmation200 = {
  email?: string;
  sent?: PostAuthSendEmailConfirmation200Sent;
};
