/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammeRequestData } from './programmeRequestData';

export interface ProgrammeRequest {
  data: ProgrammeRequestData;
}
