/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammeCoverCreatedBy } from './programmeCoverCreatedBy';
import type { ProgrammeCoverFolder } from './programmeCoverFolder';
import type { ProgrammeCoverLocalizationsItem } from './programmeCoverLocalizationsItem';
import type { ProgrammeCoverRelatedItem } from './programmeCoverRelatedItem';
import type { ProgrammeCoverUpdatedBy } from './programmeCoverUpdatedBy';

export type ProgrammeCover = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: ProgrammeCoverRelatedItem[];
  folder?: ProgrammeCoverFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: ProgrammeCoverCreatedBy;
  updatedBy?: ProgrammeCoverUpdatedBy;
  locale?: string;
  localizations?: ProgrammeCoverLocalizationsItem[];
};
