/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type ProgrammeUniverse = typeof ProgrammeUniverse[keyof typeof ProgrammeUniverse];


export const ProgrammeUniverse = {
  yoga: 'yoga',
  mindfulness: 'mindfulness',
  dialogue: 'dialogue',
} as const;
