/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type ProgrammeRequestDataUniverse = typeof ProgrammeRequestDataUniverse[keyof typeof ProgrammeRequestDataUniverse];


export const ProgrammeRequestDataUniverse = {
  yoga: 'yoga',
  mindfulness: 'mindfulness',
  dialogue: 'dialogue',
} as const;
