/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Programme } from './programme';
import type { ProgrammeResponseMeta } from './programmeResponseMeta';

export interface ProgrammeResponse {
  data?: Programme;
  meta?: ProgrammeResponseMeta;
}
