/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { ProgrammeRequestDataUniverse } from './programmeRequestDataUniverse';

export type ProgrammeRequestData = {
  title?: string;
  cover: number | string;
  description?: string;
  universe?: ProgrammeRequestDataUniverse;
  slug?: string;
  events?: (number | string)[];
  summary?: string;
  locale?: string;
  localizations?: (number | string)[];
};
