/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Programme } from './programme';
import type { ProgrammeListResponseMeta } from './programmeListResponseMeta';

export interface ProgrammeListResponse {
  data?: Programme[];
  meta?: ProgrammeListResponseMeta;
}
