/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { PutUsersPermissionsRolesRole200Ok } from './putUsersPermissionsRolesRole200Ok';

export type PutUsersPermissionsRolesRole200 = {
  ok?: PutUsersPermissionsRolesRole200Ok;
};
