/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type PutUsersPermissionsRolesRole200Ok = typeof PutUsersPermissionsRolesRole200Ok[keyof typeof PutUsersPermissionsRolesRole200Ok];


export const PutUsersPermissionsRolesRole200Ok = {
  true: true,
} as const;
