/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TemoignageAvatarCreatedBy } from './temoignageAvatarCreatedBy';
import type { TemoignageAvatarFolder } from './temoignageAvatarFolder';
import type { TemoignageAvatarLocalizationsItem } from './temoignageAvatarLocalizationsItem';
import type { TemoignageAvatarRelatedItem } from './temoignageAvatarRelatedItem';
import type { TemoignageAvatarUpdatedBy } from './temoignageAvatarUpdatedBy';

export type TemoignageAvatar = {
  id?: string | number;
  documentId?: string;
  name?: string;
  alternativeText?: string;
  caption?: string;
  focalPoint?: unknown;
  width?: number;
  height?: number;
  formats?: unknown;
  hash?: string;
  ext?: string;
  mime?: string;
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: unknown;
  related?: TemoignageAvatarRelatedItem[];
  folder?: TemoignageAvatarFolder;
  folderPath?: string;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: TemoignageAvatarCreatedBy;
  updatedBy?: TemoignageAvatarUpdatedBy;
  locale?: string;
  localizations?: TemoignageAvatarLocalizationsItem[];
};
