/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TemoignageRequestData } from './temoignageRequestData';

export interface TemoignageRequest {
  data: TemoignageRequestData;
}
