/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TemoignageRequestDataUniverse } from './temoignageRequestDataUniverse';

export type TemoignageRequestData = {
  summary: string;
  person: string;
  avatar?: number | string;
  programme?: number | string;
  event?: number | string;
  universe?: TemoignageRequestDataUniverse;
  locale?: string;
  localizations?: (number | string)[];
};
