/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { TemoignageListResponseMetaPagination } from './temoignageListResponseMetaPagination';

export type TemoignageListResponseMeta = {
  pagination?: TemoignageListResponseMetaPagination;
};
