/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Event } from './event';
import type { Programme } from './programme';
import type { TemoignageAvatar } from './temoignageAvatar';
import type { TemoignageCreatedBy } from './temoignageCreatedBy';
import type { TemoignageUniverse } from './temoignageUniverse';
import type { TemoignageUpdatedBy } from './temoignageUpdatedBy';

export interface Temoignage {
  id?: string | number;
  documentId?: string;
  summary: string;
  person: string;
  avatar?: TemoignageAvatar;
  programme?: Programme;
  event?: Event;
  universe?: TemoignageUniverse;
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  createdBy?: TemoignageCreatedBy;
  updatedBy?: TemoignageUpdatedBy;
  locale?: string;
  localizations?: Temoignage[];
}
