/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Temoignage } from './temoignage';
import type { TemoignageListResponseMeta } from './temoignageListResponseMeta';

export interface TemoignageListResponse {
  data?: Temoignage[];
  meta?: TemoignageListResponseMeta;
}
