/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type TemoignageUniverse = typeof TemoignageUniverse[keyof typeof TemoignageUniverse];


export const TemoignageUniverse = {
  yoga: 'yoga',
  mindfulness: 'mindfulness',
  dialogue: 'dialogue',
} as const;
