/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { Temoignage } from './temoignage';
import type { TemoignageResponseMeta } from './temoignageResponseMeta';

export interface TemoignageResponse {
  data?: Temoignage;
  meta?: TemoignageResponseMeta;
}
