/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */

export type TemoignageRequestDataUniverse = typeof TemoignageRequestDataUniverse[keyof typeof TemoignageRequestDataUniverse];


export const TemoignageRequestDataUniverse = {
  yoga: 'yoga',
  mindfulness: 'mindfulness',
  dialogue: 'dialogue',
} as const;
