/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsUser } from './usersPermissionsUser';

export interface UsersPermissionsUserRegistration {
  jwt?: string;
  user?: UsersPermissionsUser;
}
