/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import type { UsersPermissionsPermissionsTreeControllers } from './usersPermissionsPermissionsTreeControllers';

export interface UsersPermissionsPermissionsTree {[key: string]: {
  /** every controller of the api */
  controllers?: UsersPermissionsPermissionsTreeControllers;
}}
