/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  EventListResponse,
  EventRequest,
  EventResponse,
  GetEventsParams
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getEventsResponse200 = {
  data: EventListResponse
  status: 200
}

export type getEventsResponse400 = {
  data: Error
  status: 400
}

export type getEventsResponse401 = {
  data: Error
  status: 401
}

export type getEventsResponse403 = {
  data: Error
  status: 403
}

export type getEventsResponse404 = {
  data: Error
  status: 404
}

export type getEventsResponse500 = {
  data: Error
  status: 500
}

export type getEventsResponseSuccess = (getEventsResponse200) & {
  headers: Headers;
};
export type getEventsResponseError = (getEventsResponse400 | getEventsResponse401 | getEventsResponse403 | getEventsResponse404 | getEventsResponse500) & {
  headers: Headers;
};

export type getEventsResponse = (getEventsResponseSuccess | getEventsResponseError)

export const getGetEventsUrl = (params?: GetEventsParams,) => {
  const normalizedParams = new URLSearchParams();
  const deepObjectEntries: string[] = [];

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["populate"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }
      const deepObjectParameters = ["filters"];

    if (typeof value === 'object' && value !== null && !Array.isArray(value) && deepObjectParameters.includes(key)) {
      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subValue !== undefined) {
          deepObjectEntries.push(encodeURIComponent(key) + '[' + encodeURIComponent(subKey) + ']=' + (subValue === null ? 'null' : encodeURIComponent(String(subValue))));
        }
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = [normalizedParams.toString(), deepObjectEntries.join('&')].filter(Boolean).join('&');

  return stringifiedParams.length > 0 ? `/events?${stringifiedParams}` : `/events`
}

export const getEvents = async (params?: GetEventsParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getEventsResponse> => {

  return strapiFetch<getEventsResponse>(getGetEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEventsQueryKey = (params?: GetEventsParams,) => {
    return [
    `/events`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetEventsQueryOptions = <TData = Awaited<ReturnType<typeof getEvents>>, TError = Error>(params?: GetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvents>>> = ({ signal }) => getEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getEvents>>>
export type GetEventsQueryError = Error


export function useGetEvents<TData = Awaited<ReturnType<typeof getEvents>>, TError = Error>(
 params: undefined |  GetEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents>>,
          TError,
          Awaited<ReturnType<typeof getEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvents<TData = Awaited<ReturnType<typeof getEvents>>, TError = Error>(
 params?: GetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEvents>>,
          TError,
          Awaited<ReturnType<typeof getEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEvents<TData = Awaited<ReturnType<typeof getEvents>>, TError = Error>(
 params?: GetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEvents<TData = Awaited<ReturnType<typeof getEvents>>, TError = Error>(
 params?: GetEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEvents>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postEventsResponse200 = {
  data: EventResponse
  status: 200
}

export type postEventsResponse400 = {
  data: Error
  status: 400
}

export type postEventsResponse401 = {
  data: Error
  status: 401
}

export type postEventsResponse403 = {
  data: Error
  status: 403
}

export type postEventsResponse404 = {
  data: Error
  status: 404
}

export type postEventsResponse500 = {
  data: Error
  status: 500
}

export type postEventsResponseSuccess = (postEventsResponse200) & {
  headers: Headers;
};
export type postEventsResponseError = (postEventsResponse400 | postEventsResponse401 | postEventsResponse403 | postEventsResponse404 | postEventsResponse500) & {
  headers: Headers;
};

export type postEventsResponse = (postEventsResponseSuccess | postEventsResponseError)

export const getPostEventsUrl = () => {




  return `/events`
}

export const postEvents = async (eventRequest: EventRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<postEventsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postEventsResponse>(getPostEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(eventRequest)
  }
);}





export const getPostEventsMutationKey = () => ['postEvents'] as const;

export const getPostEventsMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,PostEventsMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,PostEventsMutationVariables, TContext> => {

const mutationKey = getPostEventsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEvents>>, PostEventsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postEvents(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostEventsMutationResult = NonNullable<Awaited<ReturnType<typeof postEvents>>>
    export type PostEventsMutationBody = EventRequest
    export type PostEventsMutationError = Error
    export type PostEventsMutationVariables = {data: EventRequest}

    export const usePostEvents = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEvents>>, TError,PostEventsMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postEvents>>,
        TError,
        PostEventsMutationVariables,
        TContext
      > => {
      return useMutation(getPostEventsMutationOptions(options), queryClient);
    }
    export type getEventsIdResponse200 = {
  data: EventResponse
  status: 200
}

export type getEventsIdResponse400 = {
  data: Error
  status: 400
}

export type getEventsIdResponse401 = {
  data: Error
  status: 401
}

export type getEventsIdResponse403 = {
  data: Error
  status: 403
}

export type getEventsIdResponse404 = {
  data: Error
  status: 404
}

export type getEventsIdResponse500 = {
  data: Error
  status: 500
}

export type getEventsIdResponseSuccess = (getEventsIdResponse200) & {
  headers: Headers;
};
export type getEventsIdResponseError = (getEventsIdResponse400 | getEventsIdResponse401 | getEventsIdResponse403 | getEventsIdResponse404 | getEventsIdResponse500) & {
  headers: Headers;
};

export type getEventsIdResponse = (getEventsIdResponseSuccess | getEventsIdResponseError)

export const getGetEventsIdUrl = (id: string,) => {




  return `/events/${id}`
}

export const getEventsId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<getEventsIdResponse> => {

  return strapiFetch<getEventsIdResponse>(getGetEventsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEventsIdQueryKey = (id: string,) => {
    return [
    `/events/${id}`
    ] as const;
    }


export const getGetEventsIdQueryOptions = <TData = Awaited<ReturnType<typeof getEventsId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventsId>>> = ({ signal }) => getEventsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getEventsId>>>
export type GetEventsIdQueryError = Error


export function useGetEventsId<TData = Awaited<ReturnType<typeof getEventsId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsId>>,
          TError,
          Awaited<ReturnType<typeof getEventsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsId<TData = Awaited<ReturnType<typeof getEventsId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsId>>,
          TError,
          Awaited<ReturnType<typeof getEventsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsId<TData = Awaited<ReturnType<typeof getEventsId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEventsId<TData = Awaited<ReturnType<typeof getEventsId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putEventsIdResponse200 = {
  data: EventResponse
  status: 200
}

export type putEventsIdResponse400 = {
  data: Error
  status: 400
}

export type putEventsIdResponse401 = {
  data: Error
  status: 401
}

export type putEventsIdResponse403 = {
  data: Error
  status: 403
}

export type putEventsIdResponse404 = {
  data: Error
  status: 404
}

export type putEventsIdResponse500 = {
  data: Error
  status: 500
}

export type putEventsIdResponseSuccess = (putEventsIdResponse200) & {
  headers: Headers;
};
export type putEventsIdResponseError = (putEventsIdResponse400 | putEventsIdResponse401 | putEventsIdResponse403 | putEventsIdResponse404 | putEventsIdResponse500) & {
  headers: Headers;
};

export type putEventsIdResponse = (putEventsIdResponseSuccess | putEventsIdResponseError)

export const getPutEventsIdUrl = (id: string,) => {




  return `/events/${id}`
}

export const putEventsId = async (id: string,
    eventRequest: EventRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<putEventsIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<putEventsIdResponse>(getPutEventsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(eventRequest)
  }
);}





export const getPutEventsIdMutationKey = () => ['putEventsId'] as const;

export const getPutEventsIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putEventsId>>, TError,PutEventsIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putEventsId>>, TError,PutEventsIdMutationVariables, TContext> => {

const mutationKey = getPutEventsIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putEventsId>>, PutEventsIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putEventsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutEventsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putEventsId>>>
    export type PutEventsIdMutationBody = EventRequest
    export type PutEventsIdMutationError = Error
    export type PutEventsIdMutationVariables = {id: string;data: EventRequest}

    export const usePutEventsId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putEventsId>>, TError,PutEventsIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putEventsId>>,
        TError,
        PutEventsIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutEventsIdMutationOptions(options), queryClient);
    }
    export type deleteEventsIdResponse200 = {
  data: number
  status: 200
}

export type deleteEventsIdResponse400 = {
  data: Error
  status: 400
}

export type deleteEventsIdResponse401 = {
  data: Error
  status: 401
}

export type deleteEventsIdResponse403 = {
  data: Error
  status: 403
}

export type deleteEventsIdResponse404 = {
  data: Error
  status: 404
}

export type deleteEventsIdResponse500 = {
  data: Error
  status: 500
}

export type deleteEventsIdResponseSuccess = (deleteEventsIdResponse200) & {
  headers: Headers;
};
export type deleteEventsIdResponseError = (deleteEventsIdResponse400 | deleteEventsIdResponse401 | deleteEventsIdResponse403 | deleteEventsIdResponse404 | deleteEventsIdResponse500) & {
  headers: Headers;
};

export type deleteEventsIdResponse = (deleteEventsIdResponseSuccess | deleteEventsIdResponseError)

export const getDeleteEventsIdUrl = (id: string,) => {




  return `/events/${id}`
}

export const deleteEventsId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<deleteEventsIdResponse> => {

  return strapiFetch<deleteEventsIdResponse>(getDeleteEventsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteEventsIdMutationKey = () => ['deleteEventsId'] as const;

export const getDeleteEventsIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventsId>>, TError,DeleteEventsIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteEventsId>>, TError,DeleteEventsIdMutationVariables, TContext> => {

const mutationKey = getDeleteEventsIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEventsId>>, DeleteEventsIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteEventsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteEventsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEventsId>>>

    export type DeleteEventsIdMutationError = Error
    export type DeleteEventsIdMutationVariables = {id: string}

    export const useDeleteEventsId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteEventsId>>, TError,DeleteEventsIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteEventsId>>,
        TError,
        DeleteEventsIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteEventsIdMutationOptions(options), queryClient);
    }
