/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetPagesParams,
  PageListResponse,
  PageRequest,
  PageResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPagesUrl = (params?: GetPagesParams,) => {
  const stringifiedParams = strapiParamsSerializer(params);

  return stringifiedParams.length > 0 ? `/pages?${stringifiedParams}` : `/pages`
}

export const getPages = async (params?: GetPagesParams, options?: Parameters<typeof strapiFetch>[1]): Promise<PageListResponse> => {

  return strapiFetch<PageListResponse>(getGetPagesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPagesQueryKey = (params?: GetPagesParams,) => {
    return [
    `/pages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPagesQueryOptions = <TData = Awaited<ReturnType<typeof getPages>>, TError = Error>(params?: GetPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPages>>> = ({ signal }) => getPages(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPagesQueryResult = NonNullable<Awaited<ReturnType<typeof getPages>>>
export type GetPagesQueryError = Error


export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = Error>(
 params: undefined |  GetPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = Error>(
 params?: GetPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPages>>,
          TError,
          Awaited<ReturnType<typeof getPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = Error>(
 params?: GetPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPages<TData = Awaited<ReturnType<typeof getPages>>, TError = Error>(
 params?: GetPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostPagesUrl = () => {


  return `/pages`
}

export const postPages = async (pageRequest: PageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<PageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PageResponse>(getPostPagesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pageRequest)
  }
);}





export const getPostPagesMutationKey = () => ['postPages'] as const;

export const getPostPagesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPages>>, TError,PostPagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPages>>, TError,PostPagesMutationVariables, TContext> => {

const mutationKey = getPostPagesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPages>>, PostPagesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postPages(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPagesMutationResult = NonNullable<Awaited<ReturnType<typeof postPages>>>
    export type PostPagesMutationBody = PageRequest
    export type PostPagesMutationError = Error
    export type PostPagesMutationVariables = {data: PageRequest}

    export const usePostPages = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPages>>, TError,PostPagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPages>>,
        TError,
        PostPagesMutationVariables,
        TContext
      > => {
      return useMutation(getPostPagesMutationOptions(options), queryClient);
    }
    export const getGetPagesIdUrl = (id: string,) => {


  return `/pages/${id}`
}

export const getPagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<PageResponse> => {

  return strapiFetch<PageResponse>(getGetPagesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPagesIdQueryKey = (id: string,) => {
    return [
    `/pages/${id}`
    ] as const;
    }


export const getGetPagesIdQueryOptions = <TData = Awaited<ReturnType<typeof getPagesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPagesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPagesId>>> = ({ signal }) => getPagesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPagesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPagesId>>>
export type GetPagesIdQueryError = Error


export function useGetPagesId<TData = Awaited<ReturnType<typeof getPagesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPagesId>>,
          TError,
          Awaited<ReturnType<typeof getPagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPagesId<TData = Awaited<ReturnType<typeof getPagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPagesId>>,
          TError,
          Awaited<ReturnType<typeof getPagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPagesId<TData = Awaited<ReturnType<typeof getPagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPagesId<TData = Awaited<ReturnType<typeof getPagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPagesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutPagesIdUrl = (id: string,) => {


  return `/pages/${id}`
}

export const putPagesId = async (id: string,
    pageRequest: PageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<PageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PageResponse>(getPutPagesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pageRequest)
  }
);}





export const getPutPagesIdMutationKey = () => ['putPagesId'] as const;

export const getPutPagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPagesId>>, TError,PutPagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putPagesId>>, TError,PutPagesIdMutationVariables, TContext> => {

const mutationKey = getPutPagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putPagesId>>, PutPagesIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putPagesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutPagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putPagesId>>>
    export type PutPagesIdMutationBody = PageRequest
    export type PutPagesIdMutationError = Error
    export type PutPagesIdMutationVariables = {id: string;data: PageRequest}

    export const usePutPagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPagesId>>, TError,PutPagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putPagesId>>,
        TError,
        PutPagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutPagesIdMutationOptions(options), queryClient);
    }
    export const getDeletePagesIdUrl = (id: string,) => {


  return `/pages/${id}`
}

export const deletePagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<number> => {

  return strapiFetch<number>(getDeletePagesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePagesIdMutationKey = () => ['deletePagesId'] as const;

export const getDeletePagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePagesId>>, TError,DeletePagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePagesId>>, TError,DeletePagesIdMutationVariables, TContext> => {

const mutationKey = getDeletePagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePagesId>>, DeletePagesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deletePagesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deletePagesId>>>

    export type DeletePagesIdMutationError = Error
    export type DeletePagesIdMutationVariables = {id: string}

    export const useDeletePagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePagesId>>, TError,DeletePagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePagesId>>,
        TError,
        DeletePagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeletePagesIdMutationOptions(options), queryClient);
    }
