/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AboutRequest,
  AboutResponse,
  Error,
  GetAboutParams
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetAboutUrl = (params?: GetAboutParams,) => {
  const stringifiedParams = strapiParamsSerializer(params);

  return stringifiedParams.length > 0 ? `/about?${stringifiedParams}` : `/about`
}

export const getAbout = async (params?: GetAboutParams, options?: Parameters<typeof strapiFetch>[1]): Promise<AboutResponse> => {

  return strapiFetch<AboutResponse>(getGetAboutUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAboutQueryKey = (params?: GetAboutParams,) => {
    return [
    `/about`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAboutQueryOptions = <TData = Awaited<ReturnType<typeof getAbout>>, TError = Error>(params?: GetAboutParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAboutQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAbout>>> = ({ signal }) => getAbout(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAboutQueryResult = NonNullable<Awaited<ReturnType<typeof getAbout>>>
export type GetAboutQueryError = Error


export function useGetAbout<TData = Awaited<ReturnType<typeof getAbout>>, TError = Error>(
 params: undefined |  GetAboutParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAbout>>,
          TError,
          Awaited<ReturnType<typeof getAbout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAbout<TData = Awaited<ReturnType<typeof getAbout>>, TError = Error>(
 params?: GetAboutParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAbout>>,
          TError,
          Awaited<ReturnType<typeof getAbout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAbout<TData = Awaited<ReturnType<typeof getAbout>>, TError = Error>(
 params?: GetAboutParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAbout<TData = Awaited<ReturnType<typeof getAbout>>, TError = Error>(
 params?: GetAboutParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAbout>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAboutQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutAboutUrl = () => {


  return `/about`
}

export const putAbout = async (aboutRequest: AboutRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<AboutResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<AboutResponse>(getPutAboutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(aboutRequest)
  }
);}





export const getPutAboutMutationKey = () => ['putAbout'] as const;

export const getPutAboutMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAbout>>, TError,PutAboutMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putAbout>>, TError,PutAboutMutationVariables, TContext> => {

const mutationKey = getPutAboutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAbout>>, PutAboutMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  putAbout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAboutMutationResult = NonNullable<Awaited<ReturnType<typeof putAbout>>>
    export type PutAboutMutationBody = AboutRequest
    export type PutAboutMutationError = Error
    export type PutAboutMutationVariables = {data: AboutRequest}

    export const usePutAbout = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAbout>>, TError,PutAboutMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAbout>>,
        TError,
        PutAboutMutationVariables,
        TContext
      > => {
      return useMutation(getPutAboutMutationOptions(options), queryClient);
    }
    export const getDeleteAboutUrl = () => {


  return `/about`
}

export const deleteAbout = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<number> => {

  return strapiFetch<number>(getDeleteAboutUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAboutMutationKey = () => ['deleteAbout'] as const;

export const getDeleteAboutMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAbout>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAbout>>, TError,void, TContext> => {

const mutationKey = getDeleteAboutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAbout>>, void> = () => {


          return  deleteAbout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAboutMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAbout>>>

    export type DeleteAboutMutationError = Error


    export const useDeleteAbout = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAbout>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAbout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteAboutMutationOptions(options), queryClient);
    }
