/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetProgrammesParams,
  ProgrammeListResponse,
  ProgrammeRequest,
  ProgrammeResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetProgrammesUrl = (params?: GetProgrammesParams,) => {
  const stringifiedParams = strapiParamsSerializer(params);

  return stringifiedParams.length > 0 ? `/programmes?${stringifiedParams}` : `/programmes`
}

export const getProgrammes = async (params?: GetProgrammesParams, options?: Parameters<typeof strapiFetch>[1]): Promise<ProgrammeListResponse> => {

  return strapiFetch<ProgrammeListResponse>(getGetProgrammesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgrammesQueryKey = (params?: GetProgrammesParams,) => {
    return [
    `/programmes`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProgrammesQueryOptions = <TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgrammesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgrammes>>> = ({ signal }) => getProgrammes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProgrammesQueryResult = NonNullable<Awaited<ReturnType<typeof getProgrammes>>>
export type GetProgrammesQueryError = Error


export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params: undefined |  GetProgrammesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammes>>,
          TError,
          Awaited<ReturnType<typeof getProgrammes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammes>>,
          TError,
          Awaited<ReturnType<typeof getProgrammes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProgrammesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostProgrammesUrl = () => {


  return `/programmes`
}

export const postProgrammes = async (programmeRequest: ProgrammeRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<ProgrammeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<ProgrammeResponse>(getPostProgrammesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(programmeRequest)
  }
);}





export const getPostProgrammesMutationKey = () => ['postProgrammes'] as const;

export const getPostProgrammesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext> => {

const mutationKey = getPostProgrammesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProgrammes>>, PostProgrammesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postProgrammes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProgrammesMutationResult = NonNullable<Awaited<ReturnType<typeof postProgrammes>>>
    export type PostProgrammesMutationBody = ProgrammeRequest
    export type PostProgrammesMutationError = Error
    export type PostProgrammesMutationVariables = {data: ProgrammeRequest}

    export const usePostProgrammes = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProgrammes>>,
        TError,
        PostProgrammesMutationVariables,
        TContext
      > => {
      return useMutation(getPostProgrammesMutationOptions(options), queryClient);
    }
    export const getGetProgrammesIdUrl = (id: string,) => {


  return `/programmes/${id}`
}

export const getProgrammesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<ProgrammeResponse> => {

  return strapiFetch<ProgrammeResponse>(getGetProgrammesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgrammesIdQueryKey = (id: string,) => {
    return [
    `/programmes/${id}`
    ] as const;
    }


export const getGetProgrammesIdQueryOptions = <TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgrammesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgrammesId>>> = ({ signal }) => getProgrammesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProgrammesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProgrammesId>>>
export type GetProgrammesIdQueryError = Error


export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammesId>>,
          TError,
          Awaited<ReturnType<typeof getProgrammesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammesId>>,
          TError,
          Awaited<ReturnType<typeof getProgrammesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProgrammesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutProgrammesIdUrl = (id: string,) => {


  return `/programmes/${id}`
}

export const putProgrammesId = async (id: string,
    programmeRequest: ProgrammeRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<ProgrammeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<ProgrammeResponse>(getPutProgrammesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(programmeRequest)
  }
);}





export const getPutProgrammesIdMutationKey = () => ['putProgrammesId'] as const;

export const getPutProgrammesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext> => {

const mutationKey = getPutProgrammesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putProgrammesId>>, PutProgrammesIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putProgrammesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutProgrammesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putProgrammesId>>>
    export type PutProgrammesIdMutationBody = ProgrammeRequest
    export type PutProgrammesIdMutationError = Error
    export type PutProgrammesIdMutationVariables = {id: string;data: ProgrammeRequest}

    export const usePutProgrammesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putProgrammesId>>,
        TError,
        PutProgrammesIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutProgrammesIdMutationOptions(options), queryClient);
    }
    export const getDeleteProgrammesIdUrl = (id: string,) => {


  return `/programmes/${id}`
}

export const deleteProgrammesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<number> => {

  return strapiFetch<number>(getDeleteProgrammesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteProgrammesIdMutationKey = () => ['deleteProgrammesId'] as const;

export const getDeleteProgrammesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext> => {

const mutationKey = getDeleteProgrammesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProgrammesId>>, DeleteProgrammesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteProgrammesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProgrammesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProgrammesId>>>

    export type DeleteProgrammesIdMutationError = Error
    export type DeleteProgrammesIdMutationVariables = {id: string}

    export const useDeleteProgrammesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProgrammesId>>,
        TError,
        DeleteProgrammesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteProgrammesIdMutationOptions(options), queryClient);
    }
