/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetProgrammesParams,
  ProgrammeListResponse,
  ProgrammeRequest,
  ProgrammeResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getProgrammesResponse200 = {
  data: ProgrammeListResponse
  status: 200
}

export type getProgrammesResponse400 = {
  data: Error
  status: 400
}

export type getProgrammesResponse401 = {
  data: Error
  status: 401
}

export type getProgrammesResponse403 = {
  data: Error
  status: 403
}

export type getProgrammesResponse404 = {
  data: Error
  status: 404
}

export type getProgrammesResponse500 = {
  data: Error
  status: 500
}

export type getProgrammesResponseSuccess = (getProgrammesResponse200) & {
  headers: Headers;
};
export type getProgrammesResponseError = (getProgrammesResponse400 | getProgrammesResponse401 | getProgrammesResponse403 | getProgrammesResponse404 | getProgrammesResponse500) & {
  headers: Headers;
};

export type getProgrammesResponse = (getProgrammesResponseSuccess | getProgrammesResponseError)

export const getGetProgrammesUrl = (params?: GetProgrammesParams,) => {
  const normalizedParams = new URLSearchParams();
  const deepObjectEntries: string[] = [];

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["populate"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }
      const deepObjectParameters = ["filters"];

    if (typeof value === 'object' && value !== null && !Array.isArray(value) && deepObjectParameters.includes(key)) {
      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subValue !== undefined) {
          deepObjectEntries.push(encodeURIComponent(key) + '[' + encodeURIComponent(subKey) + ']=' + (subValue === null ? 'null' : encodeURIComponent(String(subValue))));
        }
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = [normalizedParams.toString(), deepObjectEntries.join('&')].filter(Boolean).join('&');

  return stringifiedParams.length > 0 ? `/programmes?${stringifiedParams}` : `/programmes`
}

export const getProgrammes = async (params?: GetProgrammesParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getProgrammesResponse> => {

  return strapiFetch<getProgrammesResponse>(getGetProgrammesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgrammesQueryKey = (params?: GetProgrammesParams,) => {
    return [
    `/programmes`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProgrammesQueryOptions = <TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgrammesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgrammes>>> = ({ signal }) => getProgrammes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProgrammesQueryResult = NonNullable<Awaited<ReturnType<typeof getProgrammes>>>
export type GetProgrammesQueryError = Error


export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params: undefined |  GetProgrammesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammes>>,
          TError,
          Awaited<ReturnType<typeof getProgrammes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammes>>,
          TError,
          Awaited<ReturnType<typeof getProgrammes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProgrammes<TData = Awaited<ReturnType<typeof getProgrammes>>, TError = Error>(
 params?: GetProgrammesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammes>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProgrammesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postProgrammesResponse200 = {
  data: ProgrammeResponse
  status: 200
}

export type postProgrammesResponse400 = {
  data: Error
  status: 400
}

export type postProgrammesResponse401 = {
  data: Error
  status: 401
}

export type postProgrammesResponse403 = {
  data: Error
  status: 403
}

export type postProgrammesResponse404 = {
  data: Error
  status: 404
}

export type postProgrammesResponse500 = {
  data: Error
  status: 500
}

export type postProgrammesResponseSuccess = (postProgrammesResponse200) & {
  headers: Headers;
};
export type postProgrammesResponseError = (postProgrammesResponse400 | postProgrammesResponse401 | postProgrammesResponse403 | postProgrammesResponse404 | postProgrammesResponse500) & {
  headers: Headers;
};

export type postProgrammesResponse = (postProgrammesResponseSuccess | postProgrammesResponseError)

export const getPostProgrammesUrl = () => {




  return `/programmes`
}

export const postProgrammes = async (programmeRequest: ProgrammeRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<postProgrammesResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postProgrammesResponse>(getPostProgrammesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(programmeRequest)
  }
);}





export const getPostProgrammesMutationKey = () => ['postProgrammes'] as const;

export const getPostProgrammesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext> => {

const mutationKey = getPostProgrammesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProgrammes>>, PostProgrammesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postProgrammes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostProgrammesMutationResult = NonNullable<Awaited<ReturnType<typeof postProgrammes>>>
    export type PostProgrammesMutationBody = ProgrammeRequest
    export type PostProgrammesMutationError = Error
    export type PostProgrammesMutationVariables = {data: ProgrammeRequest}

    export const usePostProgrammes = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProgrammes>>, TError,PostProgrammesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProgrammes>>,
        TError,
        PostProgrammesMutationVariables,
        TContext
      > => {
      return useMutation(getPostProgrammesMutationOptions(options), queryClient);
    }
    export type getProgrammesIdResponse200 = {
  data: ProgrammeResponse
  status: 200
}

export type getProgrammesIdResponse400 = {
  data: Error
  status: 400
}

export type getProgrammesIdResponse401 = {
  data: Error
  status: 401
}

export type getProgrammesIdResponse403 = {
  data: Error
  status: 403
}

export type getProgrammesIdResponse404 = {
  data: Error
  status: 404
}

export type getProgrammesIdResponse500 = {
  data: Error
  status: 500
}

export type getProgrammesIdResponseSuccess = (getProgrammesIdResponse200) & {
  headers: Headers;
};
export type getProgrammesIdResponseError = (getProgrammesIdResponse400 | getProgrammesIdResponse401 | getProgrammesIdResponse403 | getProgrammesIdResponse404 | getProgrammesIdResponse500) & {
  headers: Headers;
};

export type getProgrammesIdResponse = (getProgrammesIdResponseSuccess | getProgrammesIdResponseError)

export const getGetProgrammesIdUrl = (id: string,) => {




  return `/programmes/${id}`
}

export const getProgrammesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<getProgrammesIdResponse> => {

  return strapiFetch<getProgrammesIdResponse>(getGetProgrammesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgrammesIdQueryKey = (id: string,) => {
    return [
    `/programmes/${id}`
    ] as const;
    }


export const getGetProgrammesIdQueryOptions = <TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgrammesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgrammesId>>> = ({ signal }) => getProgrammesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProgrammesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProgrammesId>>>
export type GetProgrammesIdQueryError = Error


export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammesId>>,
          TError,
          Awaited<ReturnType<typeof getProgrammesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProgrammesId>>,
          TError,
          Awaited<ReturnType<typeof getProgrammesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProgrammesId<TData = Awaited<ReturnType<typeof getProgrammesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProgrammesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProgrammesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putProgrammesIdResponse200 = {
  data: ProgrammeResponse
  status: 200
}

export type putProgrammesIdResponse400 = {
  data: Error
  status: 400
}

export type putProgrammesIdResponse401 = {
  data: Error
  status: 401
}

export type putProgrammesIdResponse403 = {
  data: Error
  status: 403
}

export type putProgrammesIdResponse404 = {
  data: Error
  status: 404
}

export type putProgrammesIdResponse500 = {
  data: Error
  status: 500
}

export type putProgrammesIdResponseSuccess = (putProgrammesIdResponse200) & {
  headers: Headers;
};
export type putProgrammesIdResponseError = (putProgrammesIdResponse400 | putProgrammesIdResponse401 | putProgrammesIdResponse403 | putProgrammesIdResponse404 | putProgrammesIdResponse500) & {
  headers: Headers;
};

export type putProgrammesIdResponse = (putProgrammesIdResponseSuccess | putProgrammesIdResponseError)

export const getPutProgrammesIdUrl = (id: string,) => {




  return `/programmes/${id}`
}

export const putProgrammesId = async (id: string,
    programmeRequest: ProgrammeRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<putProgrammesIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<putProgrammesIdResponse>(getPutProgrammesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(programmeRequest)
  }
);}





export const getPutProgrammesIdMutationKey = () => ['putProgrammesId'] as const;

export const getPutProgrammesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext> => {

const mutationKey = getPutProgrammesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putProgrammesId>>, PutProgrammesIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putProgrammesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutProgrammesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putProgrammesId>>>
    export type PutProgrammesIdMutationBody = ProgrammeRequest
    export type PutProgrammesIdMutationError = Error
    export type PutProgrammesIdMutationVariables = {id: string;data: ProgrammeRequest}

    export const usePutProgrammesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProgrammesId>>, TError,PutProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putProgrammesId>>,
        TError,
        PutProgrammesIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutProgrammesIdMutationOptions(options), queryClient);
    }
    export type deleteProgrammesIdResponse200 = {
  data: number
  status: 200
}

export type deleteProgrammesIdResponse400 = {
  data: Error
  status: 400
}

export type deleteProgrammesIdResponse401 = {
  data: Error
  status: 401
}

export type deleteProgrammesIdResponse403 = {
  data: Error
  status: 403
}

export type deleteProgrammesIdResponse404 = {
  data: Error
  status: 404
}

export type deleteProgrammesIdResponse500 = {
  data: Error
  status: 500
}

export type deleteProgrammesIdResponseSuccess = (deleteProgrammesIdResponse200) & {
  headers: Headers;
};
export type deleteProgrammesIdResponseError = (deleteProgrammesIdResponse400 | deleteProgrammesIdResponse401 | deleteProgrammesIdResponse403 | deleteProgrammesIdResponse404 | deleteProgrammesIdResponse500) & {
  headers: Headers;
};

export type deleteProgrammesIdResponse = (deleteProgrammesIdResponseSuccess | deleteProgrammesIdResponseError)

export const getDeleteProgrammesIdUrl = (id: string,) => {




  return `/programmes/${id}`
}

export const deleteProgrammesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<deleteProgrammesIdResponse> => {

  return strapiFetch<deleteProgrammesIdResponse>(getDeleteProgrammesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteProgrammesIdMutationKey = () => ['deleteProgrammesId'] as const;

export const getDeleteProgrammesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext> => {

const mutationKey = getDeleteProgrammesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProgrammesId>>, DeleteProgrammesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteProgrammesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteProgrammesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProgrammesId>>>

    export type DeleteProgrammesIdMutationError = Error
    export type DeleteProgrammesIdMutationVariables = {id: string}

    export const useDeleteProgrammesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProgrammesId>>, TError,DeleteProgrammesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProgrammesId>>,
        TError,
        DeleteProgrammesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteProgrammesIdMutationOptions(options), queryClient);
    }
