/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteUsersPermissionsRolesRole200,
  Error,
  GetUsersPermissionsPermissions200,
  GetUsersPermissionsRoles200,
  GetUsersPermissionsRolesId200,
  PostUsers201,
  PostUsersBody,
  PostUsersPermissionsRoles200,
  PutUsersId200,
  PutUsersIdBody,
  PutUsersPermissionsRolesRole200,
  UsersPermissionsRoleRequestBody,
  UsersPermissionsUser
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetUsersPermissionsPermissionsUrl = () => {


  return `/users-permissions/permissions`
}

/**
 * @summary Get default generated permissions
 */
export const getUsersPermissionsPermissions = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<GetUsersPermissionsPermissions200> => {

  return strapiFetch<GetUsersPermissionsPermissions200>(getGetUsersPermissionsPermissionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersPermissionsPermissionsQueryKey = () => {
    return [
    `/users-permissions/permissions`
    ] as const;
    }


export const getGetUsersPermissionsPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersPermissionsPermissionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>> = ({ signal }) => getUsersPermissionsPermissions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersPermissionsPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>>
export type GetUsersPermissionsPermissionsQueryError = Error


export function useGetUsersPermissionsPermissions<TData = Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsPermissions>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsPermissions<TData = Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsPermissions>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsPermissions<TData = Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get default generated permissions
 */

export function useGetUsersPermissionsPermissions<TData = Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsPermissions>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersPermissionsPermissionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetUsersPermissionsRolesUrl = () => {


  return `/users-permissions/roles`
}

/**
 * @summary List roles
 */
export const getUsersPermissionsRoles = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<GetUsersPermissionsRoles200> => {

  return strapiFetch<GetUsersPermissionsRoles200>(getGetUsersPermissionsRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersPermissionsRolesQueryKey = () => {
    return [
    `/users-permissions/roles`
    ] as const;
    }


export const getGetUsersPermissionsRolesQueryOptions = <TData = Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersPermissionsRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersPermissionsRoles>>> = ({ signal }) => getUsersPermissionsRoles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersPermissionsRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersPermissionsRoles>>>
export type GetUsersPermissionsRolesQueryError = Error


export function useGetUsersPermissionsRoles<TData = Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsRoles>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsRoles<TData = Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsRoles>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsRoles<TData = Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List roles
 */

export function useGetUsersPermissionsRoles<TData = Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRoles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersPermissionsRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostUsersPermissionsRolesUrl = () => {


  return `/users-permissions/roles`
}

/**
 * @summary Create a role
 */
export const postUsersPermissionsRoles = async (usersPermissionsRoleRequestBody: UsersPermissionsRoleRequestBody, options?: Parameters<typeof strapiFetch>[1]): Promise<PostUsersPermissionsRoles200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PostUsersPermissionsRoles200>(getPostUsersPermissionsRolesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(usersPermissionsRoleRequestBody)
  }
);}





export const getPostUsersPermissionsRolesMutationKey = () => ['postUsersPermissionsRoles'] as const;

export const getPostUsersPermissionsRolesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersPermissionsRoles>>, TError,PostUsersPermissionsRolesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersPermissionsRoles>>, TError,PostUsersPermissionsRolesMutationVariables, TContext> => {

const mutationKey = getPostUsersPermissionsRolesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersPermissionsRoles>>, PostUsersPermissionsRolesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postUsersPermissionsRoles(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersPermissionsRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersPermissionsRoles>>>
    export type PostUsersPermissionsRolesMutationBody = UsersPermissionsRoleRequestBody
    export type PostUsersPermissionsRolesMutationError = Error
    export type PostUsersPermissionsRolesMutationVariables = {data: UsersPermissionsRoleRequestBody}

    /**
 * @summary Create a role
 */
export const usePostUsersPermissionsRoles = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersPermissionsRoles>>, TError,PostUsersPermissionsRolesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersPermissionsRoles>>,
        TError,
        PostUsersPermissionsRolesMutationVariables,
        TContext
      > => {
      return useMutation(getPostUsersPermissionsRolesMutationOptions(options), queryClient);
    }
    export const getGetUsersPermissionsRolesIdUrl = (id: string,) => {


  return `/users-permissions/roles/${id}`
}

/**
 * @summary Get a role
 */
export const getUsersPermissionsRolesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<GetUsersPermissionsRolesId200> => {

  return strapiFetch<GetUsersPermissionsRolesId200>(getGetUsersPermissionsRolesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersPermissionsRolesIdQueryKey = (id: string,) => {
    return [
    `/users-permissions/roles/${id}`
    ] as const;
    }


export const getGetUsersPermissionsRolesIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersPermissionsRolesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>> = ({ signal }) => getUsersPermissionsRolesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersPermissionsRolesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>>
export type GetUsersPermissionsRolesIdQueryError = Error


export function useGetUsersPermissionsRolesId<TData = Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsRolesId>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsRolesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsRolesId<TData = Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersPermissionsRolesId>>,
          TError,
          Awaited<ReturnType<typeof getUsersPermissionsRolesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersPermissionsRolesId<TData = Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a role
 */

export function useGetUsersPermissionsRolesId<TData = Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersPermissionsRolesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersPermissionsRolesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutUsersPermissionsRolesRoleUrl = (role: string,) => {


  return `/users-permissions/roles/${role}`
}

/**
 * @summary Update a role
 */
export const putUsersPermissionsRolesRole = async (role: string,
    usersPermissionsRoleRequestBody: UsersPermissionsRoleRequestBody, options?: Parameters<typeof strapiFetch>[1]): Promise<PutUsersPermissionsRolesRole200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PutUsersPermissionsRolesRole200>(getPutUsersPermissionsRolesRoleUrl(role),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(usersPermissionsRoleRequestBody)
  }
);}





export const getPutUsersPermissionsRolesRoleMutationKey = () => ['putUsersPermissionsRolesRole'] as const;

export const getPutUsersPermissionsRolesRoleMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>, TError,PutUsersPermissionsRolesRoleMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>, TError,PutUsersPermissionsRolesRoleMutationVariables, TContext> => {

const mutationKey = getPutUsersPermissionsRolesRoleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>, PutUsersPermissionsRolesRoleMutationVariables> = (props) => {
          const {role,data} = props ?? {};

          return  putUsersPermissionsRolesRole(role,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersPermissionsRolesRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>>
    export type PutUsersPermissionsRolesRoleMutationBody = UsersPermissionsRoleRequestBody
    export type PutUsersPermissionsRolesRoleMutationError = Error
    export type PutUsersPermissionsRolesRoleMutationVariables = {role: string;data: UsersPermissionsRoleRequestBody}

    /**
 * @summary Update a role
 */
export const usePutUsersPermissionsRolesRole = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>, TError,PutUsersPermissionsRolesRoleMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersPermissionsRolesRole>>,
        TError,
        PutUsersPermissionsRolesRoleMutationVariables,
        TContext
      > => {
      return useMutation(getPutUsersPermissionsRolesRoleMutationOptions(options), queryClient);
    }
    export const getDeleteUsersPermissionsRolesRoleUrl = (role: string,) => {


  return `/users-permissions/roles/${role}`
}

/**
 * @summary Delete a role
 */
export const deleteUsersPermissionsRolesRole = async (role: string, options?: Parameters<typeof strapiFetch>[1]): Promise<DeleteUsersPermissionsRolesRole200> => {

  return strapiFetch<DeleteUsersPermissionsRolesRole200>(getDeleteUsersPermissionsRolesRoleUrl(role),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteUsersPermissionsRolesRoleMutationKey = () => ['deleteUsersPermissionsRolesRole'] as const;

export const getDeleteUsersPermissionsRolesRoleMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>, TError,DeleteUsersPermissionsRolesRoleMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>, TError,DeleteUsersPermissionsRolesRoleMutationVariables, TContext> => {

const mutationKey = getDeleteUsersPermissionsRolesRoleMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>, DeleteUsersPermissionsRolesRoleMutationVariables> = (props) => {
          const {role} = props ?? {};

          return  deleteUsersPermissionsRolesRole(role,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersPermissionsRolesRoleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>>

    export type DeleteUsersPermissionsRolesRoleMutationError = Error
    export type DeleteUsersPermissionsRolesRoleMutationVariables = {role: string}

    /**
 * @summary Delete a role
 */
export const useDeleteUsersPermissionsRolesRole = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>, TError,DeleteUsersPermissionsRolesRoleMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersPermissionsRolesRole>>,
        TError,
        DeleteUsersPermissionsRolesRoleMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteUsersPermissionsRolesRoleMutationOptions(options), queryClient);
    }
    export const getGetUsersUrl = () => {


  return `/users`
}

/**
 * @summary Get list of users
 */
export const getUsers = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<UsersPermissionsUser[]> => {

  return strapiFetch<UsersPermissionsUser[]>(getGetUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = Error


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get list of users
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostUsersUrl = () => {


  return `/users`
}

/**
 * @summary Create a user
 */
export const postUsers = async (postUsersBody: PostUsersBody, options?: Parameters<typeof strapiFetch>[1]): Promise<PostUsers201> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PostUsers201>(getPostUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postUsersBody)
  }
);}





export const getPostUsersMutationKey = () => ['postUsers'] as const;

export const getPostUsersMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,PostUsersMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,PostUsersMutationVariables, TContext> => {

const mutationKey = getPostUsersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsers>>, PostUsersMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postUsers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postUsers>>>
    export type PostUsersMutationBody = PostUsersBody
    export type PostUsersMutationError = Error
    export type PostUsersMutationVariables = {data: PostUsersBody}

    /**
 * @summary Create a user
 */
export const usePostUsers = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,PostUsersMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsers>>,
        TError,
        PostUsersMutationVariables,
        TContext
      > => {
      return useMutation(getPostUsersMutationOptions(options), queryClient);
    }
    export const getGetUsersIdUrl = (id: string,) => {


  return `/users/${id}`
}

/**
 * @summary Get a user
 */
export const getUsersId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<UsersPermissionsUser> => {

  return strapiFetch<UsersPermissionsUser>(getGetUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersIdQueryKey = (id: string,) => {
    return [
    `/users/${id}`
    ] as const;
    }


export const getGetUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsersId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersId>>> = ({ signal }) => getUsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersId>>>
export type GetUsersIdQueryError = Error


export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a user
 */

export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutUsersIdUrl = (id: string,) => {


  return `/users/${id}`
}

/**
 * @summary Update a user
 */
export const putUsersId = async (id: string,
    putUsersIdBody: PutUsersIdBody, options?: Parameters<typeof strapiFetch>[1]): Promise<PutUsersId200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<PutUsersId200>(getPutUsersIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(putUsersIdBody)
  }
);}





export const getPutUsersIdMutationKey = () => ['putUsersId'] as const;

export const getPutUsersIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,PutUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,PutUsersIdMutationVariables, TContext> => {

const mutationKey = getPutUsersIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersId>>, PutUsersIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putUsersId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersId>>>
    export type PutUsersIdMutationBody = PutUsersIdBody
    export type PutUsersIdMutationError = Error
    export type PutUsersIdMutationVariables = {id: string;data: PutUsersIdBody}

    /**
 * @summary Update a user
 */
export const usePutUsersId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,PutUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersId>>,
        TError,
        PutUsersIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutUsersIdMutationOptions(options), queryClient);
    }
    export const getDeleteUsersIdUrl = (id: string,) => {


  return `/users/${id}`
}

/**
 * @summary Delete a user
 */
export const deleteUsersId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<UsersPermissionsUser> => {

  return strapiFetch<UsersPermissionsUser>(getDeleteUsersIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteUsersIdMutationKey = () => ['deleteUsersId'] as const;

export const getDeleteUsersIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,DeleteUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,DeleteUsersIdMutationVariables, TContext> => {

const mutationKey = getDeleteUsersIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersId>>, DeleteUsersIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteUsersId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersId>>>

    export type DeleteUsersIdMutationError = Error
    export type DeleteUsersIdMutationVariables = {id: string}

    /**
 * @summary Delete a user
 */
export const useDeleteUsersId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,DeleteUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersId>>,
        TError,
        DeleteUsersIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteUsersIdMutationOptions(options), queryClient);
    }
    export const getGetUsersMeUrl = () => {


  return `/users/me`
}

/**
 * @summary Get authenticated user info
 */
export const getUsersMe = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<UsersPermissionsUser> => {

  return strapiFetch<UsersPermissionsUser>(getGetUsersMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersMeQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }


export const getGetUsersMeQueryOptions = <TData = Awaited<ReturnType<typeof getUsersMe>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMe>>> = ({ signal }) => getUsersMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMe>>>
export type GetUsersMeQueryError = Error


export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated user info
 */

export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetUsersCountUrl = () => {


  return `/users/count`
}

/**
 * @summary Get user count
 */
export const getUsersCount = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<number> => {

  return strapiFetch<number>(getGetUsersCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersCountQueryKey = () => {
    return [
    `/users/count`
    ] as const;
    }


export const getGetUsersCountQueryOptions = <TData = Awaited<ReturnType<typeof getUsersCount>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersCount>>> = ({ signal }) => getUsersCount({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersCountQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersCount>>>
export type GetUsersCountQueryError = Error


export function useGetUsersCount<TData = Awaited<ReturnType<typeof getUsersCount>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersCount>>,
          TError,
          Awaited<ReturnType<typeof getUsersCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersCount<TData = Awaited<ReturnType<typeof getUsersCount>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersCount>>,
          TError,
          Awaited<ReturnType<typeof getUsersCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersCount<TData = Awaited<ReturnType<typeof getUsersCount>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user count
 */

export function useGetUsersCount<TData = Awaited<ReturnType<typeof getUsersCount>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCount>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






