compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

injectEnvironmentFiles: []

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
