# https://github.com/yarnpkg/berry/pull/5544#issuecomment-1613661101
injectEnvironmentFiles: []

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
