defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

# Only download packages for current arch
supportedArchitectures:
  cpu:
    - current
  os:
    - current
