/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetHomeParams,
  HomeRequest,
  HomeResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getHomeResponse200 = {
  data: HomeResponse
  status: 200
}

export type getHomeResponse400 = {
  data: Error
  status: 400
}

export type getHomeResponse401 = {
  data: Error
  status: 401
}

export type getHomeResponse403 = {
  data: Error
  status: 403
}

export type getHomeResponse404 = {
  data: Error
  status: 404
}

export type getHomeResponse500 = {
  data: Error
  status: 500
}

export type getHomeResponseSuccess = (getHomeResponse200) & {
  headers: Headers;
};
export type getHomeResponseError = (getHomeResponse400 | getHomeResponse401 | getHomeResponse403 | getHomeResponse404 | getHomeResponse500) & {
  headers: Headers;
};

export type getHomeResponse = (getHomeResponseSuccess | getHomeResponseError)

export const getGetHomeUrl = (params?: GetHomeParams,) => {
  const normalizedParams = new URLSearchParams();
  const deepObjectEntries: string[] = [];

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["populate"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }
      const deepObjectParameters = ["filters"];

    if (typeof value === 'object' && value !== null && !Array.isArray(value) && deepObjectParameters.includes(key)) {
      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subValue !== undefined) {
          deepObjectEntries.push(encodeURIComponent(key) + '[' + encodeURIComponent(subKey) + ']=' + (subValue === null ? 'null' : encodeURIComponent(String(subValue))));
        }
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = [normalizedParams.toString(), deepObjectEntries.join('&')].filter(Boolean).join('&');

  return stringifiedParams.length > 0 ? `/home?${stringifiedParams}` : `/home`
}

export const getHome = async (params?: GetHomeParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getHomeResponse> => {

  return strapiFetch<getHomeResponse>(getGetHomeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHomeQueryKey = (params?: GetHomeParams,) => {
    return [
    `/home`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetHomeQueryOptions = <TData = Awaited<ReturnType<typeof getHome>>, TError = Error>(params?: GetHomeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHomeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHome>>> = ({ signal }) => getHome(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHomeQueryResult = NonNullable<Awaited<ReturnType<typeof getHome>>>
export type GetHomeQueryError = Error


export function useGetHome<TData = Awaited<ReturnType<typeof getHome>>, TError = Error>(
 params: undefined |  GetHomeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHome>>,
          TError,
          Awaited<ReturnType<typeof getHome>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHome<TData = Awaited<ReturnType<typeof getHome>>, TError = Error>(
 params?: GetHomeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHome>>,
          TError,
          Awaited<ReturnType<typeof getHome>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHome<TData = Awaited<ReturnType<typeof getHome>>, TError = Error>(
 params?: GetHomeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHome<TData = Awaited<ReturnType<typeof getHome>>, TError = Error>(
 params?: GetHomeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHome>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHomeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putHomeResponse200 = {
  data: HomeResponse
  status: 200
}

export type putHomeResponse400 = {
  data: Error
  status: 400
}

export type putHomeResponse401 = {
  data: Error
  status: 401
}

export type putHomeResponse403 = {
  data: Error
  status: 403
}

export type putHomeResponse404 = {
  data: Error
  status: 404
}

export type putHomeResponse500 = {
  data: Error
  status: 500
}

export type putHomeResponseSuccess = (putHomeResponse200) & {
  headers: Headers;
};
export type putHomeResponseError = (putHomeResponse400 | putHomeResponse401 | putHomeResponse403 | putHomeResponse404 | putHomeResponse500) & {
  headers: Headers;
};

export type putHomeResponse = (putHomeResponseSuccess | putHomeResponseError)

export const getPutHomeUrl = () => {




  return `/home`
}

export const putHome = async (homeRequest: HomeRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<putHomeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<putHomeResponse>(getPutHomeUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(homeRequest)
  }
);}





export const getPutHomeMutationKey = () => ['putHome'] as const;

export const getPutHomeMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putHome>>, TError,PutHomeMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putHome>>, TError,PutHomeMutationVariables, TContext> => {

const mutationKey = getPutHomeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putHome>>, PutHomeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  putHome(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutHomeMutationResult = NonNullable<Awaited<ReturnType<typeof putHome>>>
    export type PutHomeMutationBody = HomeRequest
    export type PutHomeMutationError = Error
    export type PutHomeMutationVariables = {data: HomeRequest}

    export const usePutHome = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putHome>>, TError,PutHomeMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putHome>>,
        TError,
        PutHomeMutationVariables,
        TContext
      > => {
      return useMutation(getPutHomeMutationOptions(options), queryClient);
    }
    export type deleteHomeResponse200 = {
  data: number
  status: 200
}

export type deleteHomeResponse400 = {
  data: Error
  status: 400
}

export type deleteHomeResponse401 = {
  data: Error
  status: 401
}

export type deleteHomeResponse403 = {
  data: Error
  status: 403
}

export type deleteHomeResponse404 = {
  data: Error
  status: 404
}

export type deleteHomeResponse500 = {
  data: Error
  status: 500
}

export type deleteHomeResponseSuccess = (deleteHomeResponse200) & {
  headers: Headers;
};
export type deleteHomeResponseError = (deleteHomeResponse400 | deleteHomeResponse401 | deleteHomeResponse403 | deleteHomeResponse404 | deleteHomeResponse500) & {
  headers: Headers;
};

export type deleteHomeResponse = (deleteHomeResponseSuccess | deleteHomeResponseError)

export const getDeleteHomeUrl = () => {




  return `/home`
}

export const deleteHome = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<deleteHomeResponse> => {

  return strapiFetch<deleteHomeResponse>(getDeleteHomeUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteHomeMutationKey = () => ['deleteHome'] as const;

export const getDeleteHomeMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHome>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteHome>>, TError,void, TContext> => {

const mutationKey = getDeleteHomeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteHome>>, void> = () => {


          return  deleteHome(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteHomeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteHome>>>

    export type DeleteHomeMutationError = Error


    export const useDeleteHome = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteHome>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteHome>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteHomeMutationOptions(options), queryClient);
    }
