/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContactRequest,
  ContactResponse,
  Error,
  GetContactParams
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getContactResponse200 = {
  data: ContactResponse
  status: 200
}

export type getContactResponse400 = {
  data: Error
  status: 400
}

export type getContactResponse401 = {
  data: Error
  status: 401
}

export type getContactResponse403 = {
  data: Error
  status: 403
}

export type getContactResponse404 = {
  data: Error
  status: 404
}

export type getContactResponse500 = {
  data: Error
  status: 500
}

export type getContactResponseSuccess = (getContactResponse200) & {
  headers: Headers;
};
export type getContactResponseError = (getContactResponse400 | getContactResponse401 | getContactResponse403 | getContactResponse404 | getContactResponse500) & {
  headers: Headers;
};

export type getContactResponse = (getContactResponseSuccess | getContactResponseError)

export const getGetContactUrl = (params?: GetContactParams,) => {
  const normalizedParams = new URLSearchParams();
  const deepObjectEntries: string[] = [];

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["populate"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }
      const deepObjectParameters = ["filters"];

    if (typeof value === 'object' && value !== null && !Array.isArray(value) && deepObjectParameters.includes(key)) {
      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subValue !== undefined) {
          deepObjectEntries.push(encodeURIComponent(key) + '[' + encodeURIComponent(subKey) + ']=' + (subValue === null ? 'null' : encodeURIComponent(String(subValue))));
        }
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = [normalizedParams.toString(), deepObjectEntries.join('&')].filter(Boolean).join('&');

  return stringifiedParams.length > 0 ? `/contact?${stringifiedParams}` : `/contact`
}

export const getContact = async (params?: GetContactParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getContactResponse> => {

  return strapiFetch<getContactResponse>(getGetContactUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetContactQueryKey = (params?: GetContactParams,) => {
    return [
    `/contact`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetContactQueryOptions = <TData = Awaited<ReturnType<typeof getContact>>, TError = Error>(params?: GetContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContact>>> = ({ signal }) => getContact(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactQueryResult = NonNullable<Awaited<ReturnType<typeof getContact>>>
export type GetContactQueryError = Error


export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = Error>(
 params: undefined |  GetContactParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContact>>,
          TError,
          Awaited<ReturnType<typeof getContact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = Error>(
 params?: GetContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContact>>,
          TError,
          Awaited<ReturnType<typeof getContact>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = Error>(
 params?: GetContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetContact<TData = Awaited<ReturnType<typeof getContact>>, TError = Error>(
 params?: GetContactParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContact>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putContactResponse200 = {
  data: ContactResponse
  status: 200
}

export type putContactResponse400 = {
  data: Error
  status: 400
}

export type putContactResponse401 = {
  data: Error
  status: 401
}

export type putContactResponse403 = {
  data: Error
  status: 403
}

export type putContactResponse404 = {
  data: Error
  status: 404
}

export type putContactResponse500 = {
  data: Error
  status: 500
}

export type putContactResponseSuccess = (putContactResponse200) & {
  headers: Headers;
};
export type putContactResponseError = (putContactResponse400 | putContactResponse401 | putContactResponse403 | putContactResponse404 | putContactResponse500) & {
  headers: Headers;
};

export type putContactResponse = (putContactResponseSuccess | putContactResponseError)

export const getPutContactUrl = () => {




  return `/contact`
}

export const putContact = async (contactRequest: ContactRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<putContactResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<putContactResponse>(getPutContactUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(contactRequest)
  }
);}





export const getPutContactMutationKey = () => ['putContact'] as const;

export const getPutContactMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContact>>, TError,PutContactMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putContact>>, TError,PutContactMutationVariables, TContext> => {

const mutationKey = getPutContactMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putContact>>, PutContactMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  putContact(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutContactMutationResult = NonNullable<Awaited<ReturnType<typeof putContact>>>
    export type PutContactMutationBody = ContactRequest
    export type PutContactMutationError = Error
    export type PutContactMutationVariables = {data: ContactRequest}

    export const usePutContact = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContact>>, TError,PutContactMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putContact>>,
        TError,
        PutContactMutationVariables,
        TContext
      > => {
      return useMutation(getPutContactMutationOptions(options), queryClient);
    }
    export type deleteContactResponse200 = {
  data: number
  status: 200
}

export type deleteContactResponse400 = {
  data: Error
  status: 400
}

export type deleteContactResponse401 = {
  data: Error
  status: 401
}

export type deleteContactResponse403 = {
  data: Error
  status: 403
}

export type deleteContactResponse404 = {
  data: Error
  status: 404
}

export type deleteContactResponse500 = {
  data: Error
  status: 500
}

export type deleteContactResponseSuccess = (deleteContactResponse200) & {
  headers: Headers;
};
export type deleteContactResponseError = (deleteContactResponse400 | deleteContactResponse401 | deleteContactResponse403 | deleteContactResponse404 | deleteContactResponse500) & {
  headers: Headers;
};

export type deleteContactResponse = (deleteContactResponseSuccess | deleteContactResponseError)

export const getDeleteContactUrl = () => {




  return `/contact`
}

export const deleteContact = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<deleteContactResponse> => {

  return strapiFetch<deleteContactResponse>(getDeleteContactUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteContactMutationKey = () => ['deleteContact'] as const;

export const getDeleteContactMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,void, TContext> => {

const mutationKey = getDeleteContactMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContact>>, void> = () => {


          return  deleteContact(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContact>>>

    export type DeleteContactMutationError = Error


    export const useDeleteContact = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,void, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContact>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteContactMutationOptions(options), queryClient);
    }
