import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import type { ReactNode } from 'react';
import { MainLayout } from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
