/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostUploadBody,
  UploadFile
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostUploadUrl = () => {


  return `/upload`
}

/**
 * Upload files
 */
export const postUpload = async (postUploadBody: PostUploadBody, options?: Parameters<typeof strapiFetch>[1]): Promise<UploadFile[]> => {
    const formData = new FormData();
if(postUploadBody.path !== undefined) {
 formData.append(`path`, postUploadBody.path);
 }
if(postUploadBody.refId !== undefined) {
 formData.append(`refId`, postUploadBody.refId);
 }
if(postUploadBody.ref !== undefined) {
 formData.append(`ref`, postUploadBody.ref);
 }
if(postUploadBody.field !== undefined) {
 formData.append(`field`, postUploadBody.field);
 }
postUploadBody.files.forEach(value => formData.append(`files`, value));

  return strapiFetch<UploadFile[]>(getPostUploadUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getPostUploadMutationKey = () => ['postUpload'] as const;

export const getPostUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUpload>>, TError,PostUploadMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postUpload>>, TError,PostUploadMutationVariables, TContext> => {

const mutationKey = getPostUploadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUpload>>, PostUploadMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postUpload>>>
    export type PostUploadMutationBody = PostUploadBody
    export type PostUploadMutationError = unknown
    export type PostUploadMutationVariables = {data: PostUploadBody}

    export const usePostUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUpload>>, TError,PostUploadMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUpload>>,
        TError,
        PostUploadMutationVariables,
        TContext
      > => {
      return useMutation(getPostUploadMutationOptions(options), queryClient);
    }
    export const getGetUploadFilesUrl = () => {


  return `/upload/files`
}

export const getUploadFiles = async ( options?: Parameters<typeof strapiFetch>[1]): Promise<UploadFile[]> => {

  return strapiFetch<UploadFile[]>(getGetUploadFilesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUploadFilesQueryKey = () => {
    return [
    `/upload/files`
    ] as const;
    }


export const getGetUploadFilesQueryOptions = <TData = Awaited<ReturnType<typeof getUploadFiles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUploadFilesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUploadFiles>>> = ({ signal }) => getUploadFiles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUploadFilesQueryResult = NonNullable<Awaited<ReturnType<typeof getUploadFiles>>>
export type GetUploadFilesQueryError = unknown


export function useGetUploadFiles<TData = Awaited<ReturnType<typeof getUploadFiles>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadFiles>>,
          TError,
          Awaited<ReturnType<typeof getUploadFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUploadFiles<TData = Awaited<ReturnType<typeof getUploadFiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadFiles>>,
          TError,
          Awaited<ReturnType<typeof getUploadFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUploadFiles<TData = Awaited<ReturnType<typeof getUploadFiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUploadFiles<TData = Awaited<ReturnType<typeof getUploadFiles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFiles>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUploadFilesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetUploadFilesIdUrl = (id: string,) => {


  return `/upload/files/${id}`
}

export const getUploadFilesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<UploadFile> => {

  return strapiFetch<UploadFile>(getGetUploadFilesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUploadFilesIdQueryKey = (id: string,) => {
    return [
    `/upload/files/${id}`
    ] as const;
    }


export const getGetUploadFilesIdQueryOptions = <TData = Awaited<ReturnType<typeof getUploadFilesId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUploadFilesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUploadFilesId>>> = ({ signal }) => getUploadFilesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUploadFilesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUploadFilesId>>>
export type GetUploadFilesIdQueryError = unknown


export function useGetUploadFilesId<TData = Awaited<ReturnType<typeof getUploadFilesId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadFilesId>>,
          TError,
          Awaited<ReturnType<typeof getUploadFilesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUploadFilesId<TData = Awaited<ReturnType<typeof getUploadFilesId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUploadFilesId>>,
          TError,
          Awaited<ReturnType<typeof getUploadFilesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUploadFilesId<TData = Awaited<ReturnType<typeof getUploadFilesId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUploadFilesId<TData = Awaited<ReturnType<typeof getUploadFilesId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUploadFilesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUploadFilesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteUploadFilesIdUrl = (id: string,) => {


  return `/upload/files/${id}`
}

export const deleteUploadFilesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<UploadFile> => {

  return strapiFetch<UploadFile>(getDeleteUploadFilesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteUploadFilesIdMutationKey = () => ['deleteUploadFilesId'] as const;

export const getDeleteUploadFilesIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUploadFilesId>>, TError,DeleteUploadFilesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUploadFilesId>>, TError,DeleteUploadFilesIdMutationVariables, TContext> => {

const mutationKey = getDeleteUploadFilesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUploadFilesId>>, DeleteUploadFilesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteUploadFilesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUploadFilesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUploadFilesId>>>

    export type DeleteUploadFilesIdMutationError = unknown
    export type DeleteUploadFilesIdMutationVariables = {id: string}

    export const useDeleteUploadFilesId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUploadFilesId>>, TError,DeleteUploadFilesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUploadFilesId>>,
        TError,
        DeleteUploadFilesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteUploadFilesIdMutationOptions(options), queryClient);
    }
