/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetTemoignagesParams,
  TemoignageListResponse,
  TemoignageRequest,
  TemoignageResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';
import { strapiParamsSerializer } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetTemoignagesUrl = (params?: GetTemoignagesParams,) => {
  const stringifiedParams = strapiParamsSerializer(params);

  return stringifiedParams.length > 0 ? `/temoignages?${stringifiedParams}` : `/temoignages`
}

export const getTemoignages = async (params?: GetTemoignagesParams, options?: Parameters<typeof strapiFetch>[1]): Promise<TemoignageListResponse> => {

  return strapiFetch<TemoignageListResponse>(getGetTemoignagesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTemoignagesQueryKey = (params?: GetTemoignagesParams,) => {
    return [
    `/temoignages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTemoignagesQueryOptions = <TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemoignagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemoignages>>> = ({ signal }) => getTemoignages(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemoignagesQueryResult = NonNullable<Awaited<ReturnType<typeof getTemoignages>>>
export type GetTemoignagesQueryError = Error


export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params: undefined |  GetTemoignagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignages>>,
          TError,
          Awaited<ReturnType<typeof getTemoignages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignages>>,
          TError,
          Awaited<ReturnType<typeof getTemoignages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemoignagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostTemoignagesUrl = () => {


  return `/temoignages`
}

export const postTemoignages = async (temoignageRequest: TemoignageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<TemoignageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<TemoignageResponse>(getPostTemoignagesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(temoignageRequest)
  }
);}





export const getPostTemoignagesMutationKey = () => ['postTemoignages'] as const;

export const getPostTemoignagesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext> => {

const mutationKey = getPostTemoignagesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTemoignages>>, PostTemoignagesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postTemoignages(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostTemoignagesMutationResult = NonNullable<Awaited<ReturnType<typeof postTemoignages>>>
    export type PostTemoignagesMutationBody = TemoignageRequest
    export type PostTemoignagesMutationError = Error
    export type PostTemoignagesMutationVariables = {data: TemoignageRequest}

    export const usePostTemoignages = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTemoignages>>,
        TError,
        PostTemoignagesMutationVariables,
        TContext
      > => {
      return useMutation(getPostTemoignagesMutationOptions(options), queryClient);
    }
    export const getGetTemoignagesIdUrl = (id: string,) => {


  return `/temoignages/${id}`
}

export const getTemoignagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<TemoignageResponse> => {

  return strapiFetch<TemoignageResponse>(getGetTemoignagesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTemoignagesIdQueryKey = (id: string,) => {
    return [
    `/temoignages/${id}`
    ] as const;
    }


export const getGetTemoignagesIdQueryOptions = <TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemoignagesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemoignagesId>>> = ({ signal }) => getTemoignagesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemoignagesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTemoignagesId>>>
export type GetTemoignagesIdQueryError = Error


export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignagesId>>,
          TError,
          Awaited<ReturnType<typeof getTemoignagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignagesId>>,
          TError,
          Awaited<ReturnType<typeof getTemoignagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemoignagesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutTemoignagesIdUrl = (id: string,) => {


  return `/temoignages/${id}`
}

export const putTemoignagesId = async (id: string,
    temoignageRequest: TemoignageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<TemoignageResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<TemoignageResponse>(getPutTemoignagesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(temoignageRequest)
  }
);}





export const getPutTemoignagesIdMutationKey = () => ['putTemoignagesId'] as const;

export const getPutTemoignagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext> => {

const mutationKey = getPutTemoignagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTemoignagesId>>, PutTemoignagesIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putTemoignagesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTemoignagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putTemoignagesId>>>
    export type PutTemoignagesIdMutationBody = TemoignageRequest
    export type PutTemoignagesIdMutationError = Error
    export type PutTemoignagesIdMutationVariables = {id: string;data: TemoignageRequest}

    export const usePutTemoignagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putTemoignagesId>>,
        TError,
        PutTemoignagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutTemoignagesIdMutationOptions(options), queryClient);
    }
    export const getDeleteTemoignagesIdUrl = (id: string,) => {


  return `/temoignages/${id}`
}

export const deleteTemoignagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<number> => {

  return strapiFetch<number>(getDeleteTemoignagesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTemoignagesIdMutationKey = () => ['deleteTemoignagesId'] as const;

export const getDeleteTemoignagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext> => {

const mutationKey = getDeleteTemoignagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTemoignagesId>>, DeleteTemoignagesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTemoignagesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTemoignagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemoignagesId>>>

    export type DeleteTemoignagesIdMutationError = Error
    export type DeleteTemoignagesIdMutationVariables = {id: string}

    export const useDeleteTemoignagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTemoignagesId>>,
        TError,
        DeleteTemoignagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTemoignagesIdMutationOptions(options), queryClient);
    }
