/**
 * Generated by orval 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetTemoignagesParams,
  TemoignageListResponse,
  TemoignageRequest,
  TemoignageResponse
} from '../model';

import { strapiFetch } from '../../lib/strapi/strapi-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getTemoignagesResponse200 = {
  data: TemoignageListResponse
  status: 200
}

export type getTemoignagesResponse400 = {
  data: Error
  status: 400
}

export type getTemoignagesResponse401 = {
  data: Error
  status: 401
}

export type getTemoignagesResponse403 = {
  data: Error
  status: 403
}

export type getTemoignagesResponse404 = {
  data: Error
  status: 404
}

export type getTemoignagesResponse500 = {
  data: Error
  status: 500
}

export type getTemoignagesResponseSuccess = (getTemoignagesResponse200) & {
  headers: Headers;
};
export type getTemoignagesResponseError = (getTemoignagesResponse400 | getTemoignagesResponse401 | getTemoignagesResponse403 | getTemoignagesResponse404 | getTemoignagesResponse500) & {
  headers: Headers;
};

export type getTemoignagesResponse = (getTemoignagesResponseSuccess | getTemoignagesResponseError)

export const getGetTemoignagesUrl = (params?: GetTemoignagesParams,) => {
  const normalizedParams = new URLSearchParams();
  const deepObjectEntries: string[] = [];

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["populate"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }
      const deepObjectParameters = ["filters"];

    if (typeof value === 'object' && value !== null && !Array.isArray(value) && deepObjectParameters.includes(key)) {
      Object.entries(value).forEach(([subKey, subValue]) => {
        if (subValue !== undefined) {
          deepObjectEntries.push(encodeURIComponent(key) + '[' + encodeURIComponent(subKey) + ']=' + (subValue === null ? 'null' : encodeURIComponent(String(subValue))));
        }
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = [normalizedParams.toString(), deepObjectEntries.join('&')].filter(Boolean).join('&');

  return stringifiedParams.length > 0 ? `/temoignages?${stringifiedParams}` : `/temoignages`
}

export const getTemoignages = async (params?: GetTemoignagesParams, options?: Parameters<typeof strapiFetch>[1]): Promise<getTemoignagesResponse> => {

  return strapiFetch<getTemoignagesResponse>(getGetTemoignagesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTemoignagesQueryKey = (params?: GetTemoignagesParams,) => {
    return [
    `/temoignages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTemoignagesQueryOptions = <TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemoignagesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemoignages>>> = ({ signal }) => getTemoignages(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemoignagesQueryResult = NonNullable<Awaited<ReturnType<typeof getTemoignages>>>
export type GetTemoignagesQueryError = Error


export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params: undefined |  GetTemoignagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignages>>,
          TError,
          Awaited<ReturnType<typeof getTemoignages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignages>>,
          TError,
          Awaited<ReturnType<typeof getTemoignages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTemoignages<TData = Awaited<ReturnType<typeof getTemoignages>>, TError = Error>(
 params?: GetTemoignagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignages>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemoignagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postTemoignagesResponse200 = {
  data: TemoignageResponse
  status: 200
}

export type postTemoignagesResponse400 = {
  data: Error
  status: 400
}

export type postTemoignagesResponse401 = {
  data: Error
  status: 401
}

export type postTemoignagesResponse403 = {
  data: Error
  status: 403
}

export type postTemoignagesResponse404 = {
  data: Error
  status: 404
}

export type postTemoignagesResponse500 = {
  data: Error
  status: 500
}

export type postTemoignagesResponseSuccess = (postTemoignagesResponse200) & {
  headers: Headers;
};
export type postTemoignagesResponseError = (postTemoignagesResponse400 | postTemoignagesResponse401 | postTemoignagesResponse403 | postTemoignagesResponse404 | postTemoignagesResponse500) & {
  headers: Headers;
};

export type postTemoignagesResponse = (postTemoignagesResponseSuccess | postTemoignagesResponseError)

export const getPostTemoignagesUrl = () => {




  return `/temoignages`
}

export const postTemoignages = async (temoignageRequest: TemoignageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<postTemoignagesResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<postTemoignagesResponse>(getPostTemoignagesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(temoignageRequest)
  }
);}





export const getPostTemoignagesMutationKey = () => ['postTemoignages'] as const;

export const getPostTemoignagesMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext> => {

const mutationKey = getPostTemoignagesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTemoignages>>, PostTemoignagesMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postTemoignages(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostTemoignagesMutationResult = NonNullable<Awaited<ReturnType<typeof postTemoignages>>>
    export type PostTemoignagesMutationBody = TemoignageRequest
    export type PostTemoignagesMutationError = Error
    export type PostTemoignagesMutationVariables = {data: TemoignageRequest}

    export const usePostTemoignages = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTemoignages>>, TError,PostTemoignagesMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTemoignages>>,
        TError,
        PostTemoignagesMutationVariables,
        TContext
      > => {
      return useMutation(getPostTemoignagesMutationOptions(options), queryClient);
    }
    export type getTemoignagesIdResponse200 = {
  data: TemoignageResponse
  status: 200
}

export type getTemoignagesIdResponse400 = {
  data: Error
  status: 400
}

export type getTemoignagesIdResponse401 = {
  data: Error
  status: 401
}

export type getTemoignagesIdResponse403 = {
  data: Error
  status: 403
}

export type getTemoignagesIdResponse404 = {
  data: Error
  status: 404
}

export type getTemoignagesIdResponse500 = {
  data: Error
  status: 500
}

export type getTemoignagesIdResponseSuccess = (getTemoignagesIdResponse200) & {
  headers: Headers;
};
export type getTemoignagesIdResponseError = (getTemoignagesIdResponse400 | getTemoignagesIdResponse401 | getTemoignagesIdResponse403 | getTemoignagesIdResponse404 | getTemoignagesIdResponse500) & {
  headers: Headers;
};

export type getTemoignagesIdResponse = (getTemoignagesIdResponseSuccess | getTemoignagesIdResponseError)

export const getGetTemoignagesIdUrl = (id: string,) => {




  return `/temoignages/${id}`
}

export const getTemoignagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<getTemoignagesIdResponse> => {

  return strapiFetch<getTemoignagesIdResponse>(getGetTemoignagesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTemoignagesIdQueryKey = (id: string,) => {
    return [
    `/temoignages/${id}`
    ] as const;
    }


export const getGetTemoignagesIdQueryOptions = <TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemoignagesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemoignagesId>>> = ({ signal }) => getTemoignagesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemoignagesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTemoignagesId>>>
export type GetTemoignagesIdQueryError = Error


export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignagesId>>,
          TError,
          Awaited<ReturnType<typeof getTemoignagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemoignagesId>>,
          TError,
          Awaited<ReturnType<typeof getTemoignagesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTemoignagesId<TData = Awaited<ReturnType<typeof getTemoignagesId>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemoignagesId>>, TError, TData>>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemoignagesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putTemoignagesIdResponse200 = {
  data: TemoignageResponse
  status: 200
}

export type putTemoignagesIdResponse400 = {
  data: Error
  status: 400
}

export type putTemoignagesIdResponse401 = {
  data: Error
  status: 401
}

export type putTemoignagesIdResponse403 = {
  data: Error
  status: 403
}

export type putTemoignagesIdResponse404 = {
  data: Error
  status: 404
}

export type putTemoignagesIdResponse500 = {
  data: Error
  status: 500
}

export type putTemoignagesIdResponseSuccess = (putTemoignagesIdResponse200) & {
  headers: Headers;
};
export type putTemoignagesIdResponseError = (putTemoignagesIdResponse400 | putTemoignagesIdResponse401 | putTemoignagesIdResponse403 | putTemoignagesIdResponse404 | putTemoignagesIdResponse500) & {
  headers: Headers;
};

export type putTemoignagesIdResponse = (putTemoignagesIdResponseSuccess | putTemoignagesIdResponseError)

export const getPutTemoignagesIdUrl = (id: string,) => {




  return `/temoignages/${id}`
}

export const putTemoignagesId = async (id: string,
    temoignageRequest: TemoignageRequest, options?: Parameters<typeof strapiFetch>[1]): Promise<putTemoignagesIdResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return strapiFetch<putTemoignagesIdResponse>(getPutTemoignagesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(temoignageRequest)
  }
);}





export const getPutTemoignagesIdMutationKey = () => ['putTemoignagesId'] as const;

export const getPutTemoignagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext> => {

const mutationKey = getPutTemoignagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTemoignagesId>>, PutTemoignagesIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putTemoignagesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutTemoignagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putTemoignagesId>>>
    export type PutTemoignagesIdMutationBody = TemoignageRequest
    export type PutTemoignagesIdMutationError = Error
    export type PutTemoignagesIdMutationVariables = {id: string;data: TemoignageRequest}

    export const usePutTemoignagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTemoignagesId>>, TError,PutTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putTemoignagesId>>,
        TError,
        PutTemoignagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutTemoignagesIdMutationOptions(options), queryClient);
    }
    export type deleteTemoignagesIdResponse200 = {
  data: number
  status: 200
}

export type deleteTemoignagesIdResponse400 = {
  data: Error
  status: 400
}

export type deleteTemoignagesIdResponse401 = {
  data: Error
  status: 401
}

export type deleteTemoignagesIdResponse403 = {
  data: Error
  status: 403
}

export type deleteTemoignagesIdResponse404 = {
  data: Error
  status: 404
}

export type deleteTemoignagesIdResponse500 = {
  data: Error
  status: 500
}

export type deleteTemoignagesIdResponseSuccess = (deleteTemoignagesIdResponse200) & {
  headers: Headers;
};
export type deleteTemoignagesIdResponseError = (deleteTemoignagesIdResponse400 | deleteTemoignagesIdResponse401 | deleteTemoignagesIdResponse403 | deleteTemoignagesIdResponse404 | deleteTemoignagesIdResponse500) & {
  headers: Headers;
};

export type deleteTemoignagesIdResponse = (deleteTemoignagesIdResponseSuccess | deleteTemoignagesIdResponseError)

export const getDeleteTemoignagesIdUrl = (id: string,) => {




  return `/temoignages/${id}`
}

export const deleteTemoignagesId = async (id: string, options?: Parameters<typeof strapiFetch>[1]): Promise<deleteTemoignagesIdResponse> => {

  return strapiFetch<deleteTemoignagesIdResponse>(getDeleteTemoignagesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTemoignagesIdMutationKey = () => ['deleteTemoignagesId'] as const;

export const getDeleteTemoignagesIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext> => {

const mutationKey = getDeleteTemoignagesIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTemoignagesId>>, DeleteTemoignagesIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteTemoignagesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTemoignagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemoignagesId>>>

    export type DeleteTemoignagesIdMutationError = Error
    export type DeleteTemoignagesIdMutationVariables = {id: string}

    export const useDeleteTemoignagesId = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemoignagesId>>, TError,DeleteTemoignagesIdMutationVariables, TContext>, request?: SecondParameter<typeof strapiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTemoignagesId>>,
        TError,
        DeleteTemoignagesIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteTemoignagesIdMutationOptions(options), queryClient);
    }
