name: CI-strapi-build

on:
  push:
    branches:
      - 'main'

env:
  LATEST_TAG: belgattitude/mindfulness-strapi:latest

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: strapi

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: false
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          load: true
          context: "{{defaultContext}}:strapi"
          tags: |
            ${{ env.LATEST_TAG }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Inspect
        run: |
          docker image inspect ${{ env.LATEST_TAG }}