name: CI-strapi

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - 'strapi'
      - '.github/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        shell: bash
        working-directory: strapi

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: ${{ github.workspace }}/strapi

      - name: Check duplicates
        run: yarn dedupe --check

      #- name: Typecheck
      #  run: yarn typecheck

      #- name: ESLint checks
      #  run: yarn lint

      #- name: Unit tests
      #  run: yarn test-unit

      - name: Build strapi
        run: yarn build
        env:
          DATABASE_FILENAME: data/mindfulness.sqlite.db
