name: CI-strapi-docker

on:
  push:
    branches:
      - 'main'

env:
  LATEST_TAG: belgattitude/mindfulness-strapi:latest

permissions:
  contents: read

jobs:
  docker:
    # if main branch not protected
    #if: ${{ github.repository == 'belgattitude/mindfulness' && contains('refs/heads/main',github.ref)}}
    runs-on: ubuntu-latest
    name: Strapi docker build
    defaults:
      run:
        shell: bash
        working-directory: strapi

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: false
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          load: true
          context: "./strapi"
          tags: |
            ${{ env.LATEST_TAG }}
          build-args: |
            "DATABASE_FILENAME=data/mindfulness-build.sqlite.db"
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker image inspect ${{ env.LATEST_TAG }}