name: Release Strapi

on:
  push:
    branches: [main]

env:
  IMAGE: belgattitude/mindfulness-strapi

permissions:
  contents: read

jobs:
  docker:
    # if main branch not protected
    #if: ${{ github.repository == 'belgattitude/mindfulness' && contains('refs/heads/main',github.ref)}}
    runs-on: ubuntu-latest
    name: Strapi docker build
    defaults:
      run:
        shell: bash
        working-directory: strapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        # Disabled for now... cheaper to self-host, use github repo or upload
        if: false
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          load: true
          context: './strapi'
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "DATABASE_FILENAME=data/mindfulness-build.sqlite.db"
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker image inspect ${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
