compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.48.cjs
