compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current

