import { defineConfig } from "orval";

/**
 * React Query hooks for the strapi REST api, generated from the OpenAPI spec
 * written by the strapi documentation plugin (pnpm codegen-openapi).
 * The spec is regenerated by `pnpm develop` in strapi when content types change.
 */
export default defineConfig({
  strapi: {
    input: {
      target:
        "../strapi/src/extensions/documentation/documentation/1.0.0/full_documentation.json",
      override: {
        // The upload plugin documents `/upload?id={id}`: a query string in a
        // path is invalid OpenAPI (POST /upload with an id is still generated)
        transformer: (spec) => {
          const { "/upload?id={id}": _invalid, ...paths } = spec.paths ?? {};
          return { ...spec, paths };
        },
      },
    },
    output: {
      client: "react-query",
      httpClient: "fetch",
      // One folder per strapi content type, models in src/openapi/model
      mode: "tags-split",
      target: "./src/openapi/strapi.ts",
      schemas: "./src/openapi/model",
      clean: true,
      override: {
        // Return the response body only (plain json): it can be dehydrated
        // from server components, errors are thrown by strapiFetch
        fetch: {
          includeHttpResponseReturnType: false,
        },
        mutator: {
          path: "./src/lib/strapi/strapi-fetch.ts",
          name: "strapiFetch",
        },
        paramsSerializer: {
          path: "./src/lib/strapi/strapi-fetch.ts",
          name: "strapiParamsSerializer",
        },
      },
    },
  },
});
