import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    // Generated by graphql-codegen (yarn codegen, yarn codegen-schema)
    "src/gql/**",
    "schema.graphql",
    ".yarn/**",
  ],
});
