import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  ignorePatterns: [
    ...(ultracite.ignorePatterns ?? []),
    // Generated by orval (pnpm codegen-openapi)
    "src/openapi/**",
    ".yarn/**",
  ],
});
