import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";
import vitest from "ultracite/oxlint/vitest";

export default defineConfig({
  extends: [core, react, next, vitest],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by orval (pnpm codegen-openapi)
    "src/openapi/**",
    ".yarn/**",
  ],
  jsPlugins: ["oxlint-tailwindcss"],
  overrides: [
    {
      // Next.js types redirects() and headers() as returning a promise
      files: ["next.config.mjs"],
      rules: {
        "require-await": "off",
      },
    },
  ],
  rules: {
    // Components use PascalCase file names
    "unicorn/filename-case": "off",
    "sort-keys": "off",
    // Tailwind - Correctness
    "tailwindcss/no-unknown-classes": "error",
    "tailwindcss/no-duplicate-classes": "error",
    "tailwindcss/no-conflicting-classes": "error",
    "tailwindcss/no-deprecated-classes": "error",
    "tailwindcss/no-unnecessary-whitespace": "error",
    "tailwindcss/no-dark-without-light": "warn",
    "tailwindcss/no-contradicting-variants": "warn",
    // Style
    "tailwindcss/enforce-canonical": "warn",
    // Class order is handled by oxfmt (sortTailwindcss in the ultracite preset)
    "tailwindcss/enforce-sort-order": "off",
    "tailwindcss/enforce-shorthand": "warn",
    "tailwindcss/enforce-consistent-important-position": "warn",
    "tailwindcss/enforce-negative-arbitrary-values": "warn",
    "tailwindcss/enforce-consistent-variable-syntax": "warn",
    "tailwindcss/consistent-variant-order": "warn",
    // Restrictions
    "tailwindcss/no-hardcoded-colors": "warn",
    "tailwindcss/no-unnecessary-arbitrary-value": "warn",
  },
  settings: {
    tailwindcss: {
      entryPoint: "src/styles/globals.css",
    },
  },
});
