type About {
  cover: UploadFile
  createdAt: DateTime
  description: String
  documentId: ID!
  publishedAt: DateTime
  summary: String
  title: String!
  updatedAt: DateTime
}

input AboutInput {
  cover: ID
  description: String
  locale: String
  publishedAt: DateTime
  summary: String
  title: String
}

input BooleanFilterInput {
  and: [Boolean]
  between: [Boolean]
  contains: Boolean
  containsi: Boolean
  endsWith: Boolean
  eq: Boolean
  eqi: Boolean
  gt: Boolean
  gte: Boolean
  in: [Boolean]
  lt: Boolean
  lte: Boolean
  ne: Boolean
  nei: Boolean
  not: BooleanFilterInput
  notContains: Boolean
  notContainsi: Boolean
  notIn: [Boolean]
  notNull: Boolean
  null: Boolean
  or: [Boolean]
  startsWith: Boolean
}

type Contact {
  cover: UploadFile
  createdAt: DateTime
  description: String
  documentId: ID!
  email: String
  phone: String
  publishedAt: DateTime
  summary: String
  title: String
  updatedAt: DateTime
}

input ContactInput {
  cover: ID
  description: String
  email: String
  locale: String
  phone: String
  publishedAt: DateTime
  summary: String
  title: String
}

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

input DateTimeFilterInput {
  and: [DateTime]
  between: [DateTime]
  contains: DateTime
  containsi: DateTime
  endsWith: DateTime
  eq: DateTime
  eqi: DateTime
  gt: DateTime
  gte: DateTime
  in: [DateTime]
  lt: DateTime
  lte: DateTime
  ne: DateTime
  nei: DateTime
  not: DateTimeFilterInput
  notContains: DateTime
  notContainsi: DateTime
  notIn: [DateTime]
  notNull: Boolean
  null: Boolean
  or: [DateTime]
  startsWith: DateTime
}

type DeleteMutationResponse {
  documentId: ID!
}

enum ENUM_EVENT_EVENTTYPE {
  cours_reguliers
  programmes_et_cycles
  stages_et_retraites
}

enum ENUM_EVENT_UNIVERSE {
  dialogue
  mindfulness
  yoga
}

enum ENUM_PROGRAMME_UNIVERSE {
  dialogue
  mindfulness
  yoga
}

enum ENUM_TEMOIGNAGE_UNIVERSE {
  dialogue
  mindfulness
  yoga
}

type Event {
  cover: UploadFile!
  createdAt: DateTime
  description: String!
  displayTitle: String
  documentId: ID!
  endAt: DateTime!
  eventType: ENUM_EVENT_EVENTTYPE!
  facebookLink: String
  flyer: UploadFile
  location: String
  online: Boolean!
  organizers: String
  programmes(filters: ProgrammeFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [Programme]!
  programmes_connection(filters: ProgrammeFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): ProgrammeRelationResponseCollection
  publishedAt: DateTime
  slug: String!
  startAt: DateTime!
  summary: String
  title: String!
  universe: ENUM_EVENT_UNIVERSE
  updatedAt: DateTime
}

type EventEntityResponseCollection {
  nodes: [Event!]!
  pageInfo: Pagination!
}

input EventFiltersInput {
  and: [EventFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  displayTitle: StringFilterInput
  documentId: IDFilterInput
  endAt: DateTimeFilterInput
  eventType: StringFilterInput
  facebookLink: StringFilterInput
  location: StringFilterInput
  not: EventFiltersInput
  online: BooleanFilterInput
  or: [EventFiltersInput]
  organizers: StringFilterInput
  programmes: ProgrammeFiltersInput
  publishedAt: DateTimeFilterInput
  slug: StringFilterInput
  startAt: DateTimeFilterInput
  summary: StringFilterInput
  title: StringFilterInput
  universe: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input EventInput {
  cover: ID
  description: String
  displayTitle: String
  endAt: DateTime
  eventType: ENUM_EVENT_EVENTTYPE
  facebookLink: String
  flyer: ID
  locale: String
  location: String
  online: Boolean
  organizers: String
  programmes: [ID]
  publishedAt: DateTime
  slug: String
  startAt: DateTime
  summary: String
  title: String
  universe: ENUM_EVENT_UNIVERSE
}

type EventRelationResponseCollection {
  nodes: [Event!]!
}

input FileInfoInput {
  alternativeText: String
  caption: String
  name: String
}

input FloatFilterInput {
  and: [Float]
  between: [Float]
  contains: Float
  containsi: Float
  endsWith: Float
  eq: Float
  eqi: Float
  gt: Float
  gte: Float
  in: [Float]
  lt: Float
  lte: Float
  ne: Float
  nei: Float
  not: FloatFilterInput
  notContains: Float
  notContainsi: Float
  notIn: [Float]
  notNull: Boolean
  null: Boolean
  or: [Float]
  startsWith: Float
}

union GenericMorph = About | Contact | Event | Home | I18NLocale | Page | Programme | ReviewWorkflowsWorkflow | ReviewWorkflowsWorkflowStage | Temoignage | UploadFile | UsersPermissionsPermission | UsersPermissionsRole | UsersPermissionsUser

type Home {
  createdAt: DateTime
  documentId: ID!
  introduction: String
  publishedAt: DateTime
  updatedAt: DateTime
}

input HomeInput {
  introduction: String
  locale: String
  publishedAt: DateTime
}

type I18NLocale {
  code: String
  createdAt: DateTime
  documentId: ID!
  name: String
  publishedAt: DateTime
  updatedAt: DateTime
}

type I18NLocaleEntityResponseCollection {
  nodes: [I18NLocale!]!
  pageInfo: Pagination!
}

input I18NLocaleFiltersInput {
  and: [I18NLocaleFiltersInput]
  code: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  name: StringFilterInput
  not: I18NLocaleFiltersInput
  or: [I18NLocaleFiltersInput]
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
}

input IDFilterInput {
  and: [ID]
  between: [ID]
  contains: ID
  containsi: ID
  endsWith: ID
  eq: ID
  eqi: ID
  gt: ID
  gte: ID
  in: [ID]
  lt: ID
  lte: ID
  ne: ID
  nei: ID
  not: IDFilterInput
  notContains: ID
  notContainsi: ID
  notIn: [ID]
  notNull: Boolean
  null: Boolean
  or: [ID]
  startsWith: ID
}

input IntFilterInput {
  and: [Int]
  between: [Int]
  contains: Int
  containsi: Int
  endsWith: Int
  eq: Int
  eqi: Int
  gt: Int
  gte: Int
  in: [Int]
  lt: Int
  lte: Int
  ne: Int
  nei: Int
  not: IntFilterInput
  notContains: Int
  notContainsi: Int
  notIn: [Int]
  notNull: Boolean
  null: Boolean
  or: [Int]
  startsWith: Int
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

input JSONFilterInput {
  and: [JSON]
  between: [JSON]
  contains: JSON
  containsi: JSON
  endsWith: JSON
  eq: JSON
  eqi: JSON
  gt: JSON
  gte: JSON
  in: [JSON]
  lt: JSON
  lte: JSON
  ne: JSON
  nei: JSON
  not: JSONFilterInput
  notContains: JSON
  notContainsi: JSON
  notIn: [JSON]
  notNull: Boolean
  null: Boolean
  or: [JSON]
  startsWith: JSON
}

type Mutation {
  """Change user password. Confirm with the current password."""
  changePassword(currentPassword: String!, password: String!, passwordConfirmation: String!): UsersPermissionsLoginPayload
  createEvent(data: EventInput!, status: PublicationStatus = PUBLISHED): Event
  createPage(data: PageInput!, status: PublicationStatus = PUBLISHED): Page
  createProgramme(data: ProgrammeInput!, status: PublicationStatus = PUBLISHED): Programme
  createReviewWorkflowsWorkflow(data: ReviewWorkflowsWorkflowInput!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  createReviewWorkflowsWorkflowStage(data: ReviewWorkflowsWorkflowStageInput!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  createTemoignage(data: TemoignageInput!, status: PublicationStatus = PUBLISHED): Temoignage

  """Create a new role"""
  createUsersPermissionsRole(data: UsersPermissionsRoleInput!): UsersPermissionsCreateRolePayload

  """Create a new user"""
  createUsersPermissionsUser(data: UsersPermissionsUserInput!): UsersPermissionsUserEntityResponse!
  deleteAbout: DeleteMutationResponse
  deleteContact: DeleteMutationResponse
  deleteEvent(documentId: ID!): DeleteMutationResponse
  deleteHome: DeleteMutationResponse
  deletePage(documentId: ID!): DeleteMutationResponse
  deleteProgramme(documentId: ID!): DeleteMutationResponse
  deleteReviewWorkflowsWorkflow(documentId: ID!): DeleteMutationResponse
  deleteReviewWorkflowsWorkflowStage(documentId: ID!): DeleteMutationResponse
  deleteTemoignage(documentId: ID!): DeleteMutationResponse
  deleteUploadFile(id: ID!): UploadFile

  """Delete an existing role"""
  deleteUsersPermissionsRole(id: ID!): UsersPermissionsDeleteRolePayload

  """Delete an existing user"""
  deleteUsersPermissionsUser(id: ID!): UsersPermissionsUserEntityResponse!

  """Confirm an email users email address"""
  emailConfirmation(confirmation: String!): UsersPermissionsLoginPayload

  """Request a reset password token"""
  forgotPassword(email: String!): UsersPermissionsPasswordPayload
  login(input: UsersPermissionsLoginInput!): UsersPermissionsLoginPayload!

  """Register a user"""
  register(input: UsersPermissionsRegisterInput!): UsersPermissionsLoginPayload!

  """
  Reset user password. Confirm with a code (resetToken from forgotPassword)
  """
  resetPassword(code: String!, password: String!, passwordConfirmation: String!): UsersPermissionsLoginPayload
  updateAbout(data: AboutInput!, status: PublicationStatus = PUBLISHED): About
  updateContact(data: ContactInput!, status: PublicationStatus = PUBLISHED): Contact
  updateEvent(data: EventInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Event
  updateHome(data: HomeInput!, status: PublicationStatus = PUBLISHED): Home
  updatePage(data: PageInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Page
  updateProgramme(data: ProgrammeInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Programme
  updateReviewWorkflowsWorkflow(data: ReviewWorkflowsWorkflowInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  updateReviewWorkflowsWorkflowStage(data: ReviewWorkflowsWorkflowStageInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  updateTemoignage(data: TemoignageInput!, documentId: ID!, status: PublicationStatus = PUBLISHED): Temoignage
  updateUploadFile(id: ID!, info: FileInfoInput): UploadFile!

  """Update an existing role"""
  updateUsersPermissionsRole(data: UsersPermissionsRoleInput!, id: ID!): UsersPermissionsUpdateRolePayload

  """Update an existing user"""
  updateUsersPermissionsUser(data: UsersPermissionsUserInput!, id: ID!): UsersPermissionsUserEntityResponse!
}

type Page {
  cover: UploadFile
  createdAt: DateTime
  documentId: ID!
  introduction: String
  programmes(filters: ProgrammeFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [Programme]!
  programmes_connection(filters: ProgrammeFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): ProgrammeRelationResponseCollection
  publishedAt: DateTime
  slug: String!
  summary: String
  title: String!
  updatedAt: DateTime
}

type PageEntityResponseCollection {
  nodes: [Page!]!
  pageInfo: Pagination!
}

input PageFiltersInput {
  and: [PageFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  introduction: StringFilterInput
  not: PageFiltersInput
  or: [PageFiltersInput]
  programmes: ProgrammeFiltersInput
  publishedAt: DateTimeFilterInput
  slug: StringFilterInput
  summary: StringFilterInput
  title: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input PageInput {
  cover: ID
  introduction: String
  locale: String
  programmes: [ID]
  publishedAt: DateTime
  slug: String
  summary: String
  title: String
}

type Pagination {
  page: Int!
  pageCount: Int!
  pageSize: Int!
  total: Int!
}

input PaginationArg {
  limit: Int
  page: Int
  pageSize: Int
  start: Int
}

type Programme {
  cover: UploadFile!
  createdAt: DateTime
  description: String
  documentId: ID!
  events(filters: EventFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [Event]!
  events_connection(filters: EventFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): EventRelationResponseCollection
  publishedAt: DateTime
  slug: String
  summary: String
  title: String
  universe: ENUM_PROGRAMME_UNIVERSE
  updatedAt: DateTime
}

type ProgrammeEntityResponseCollection {
  nodes: [Programme!]!
  pageInfo: Pagination!
}

input ProgrammeFiltersInput {
  and: [ProgrammeFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  events: EventFiltersInput
  not: ProgrammeFiltersInput
  or: [ProgrammeFiltersInput]
  publishedAt: DateTimeFilterInput
  slug: StringFilterInput
  summary: StringFilterInput
  title: StringFilterInput
  universe: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input ProgrammeInput {
  cover: ID
  description: String
  events: [ID]
  locale: String
  publishedAt: DateTime
  slug: String
  summary: String
  title: String
  universe: ENUM_PROGRAMME_UNIVERSE
}

type ProgrammeRelationResponseCollection {
  nodes: [Programme!]!
}

enum PublicationFilter {
  HAS_PUBLISHED_VERSION
  HAS_PUBLISHED_VERSION_DOCUMENT
  MODIFIED
  NEVER_PUBLISHED
  NEVER_PUBLISHED_DOCUMENT
  PUBLISHED_WITHOUT_DRAFT
  PUBLISHED_WITH_DRAFT
  UNMODIFIED
}

enum PublicationStatus {
  DRAFT
  PUBLISHED
}

type Query {
  about(hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): About
  contact(hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Contact
  event(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Event
  events(filters: EventFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Event]!
  events_connection(filters: EventFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): EventEntityResponseCollection
  home(hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Home
  i18NLocale(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): I18NLocale
  i18NLocales(filters: I18NLocaleFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [I18NLocale]!
  i18NLocales_connection(filters: I18NLocaleFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): I18NLocaleEntityResponseCollection
  me: UsersPermissionsMe
  page(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Page
  pages(filters: PageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Page]!
  pages_connection(filters: PageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): PageEntityResponseCollection
  programme(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Programme
  programmes(filters: ProgrammeFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Programme]!
  programmes_connection(filters: ProgrammeFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): ProgrammeEntityResponseCollection
  reviewWorkflowsWorkflow(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflow
  reviewWorkflowsWorkflowStage(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStage
  reviewWorkflowsWorkflowStages(filters: ReviewWorkflowsWorkflowStageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [ReviewWorkflowsWorkflowStage]!
  reviewWorkflowsWorkflowStages_connection(filters: ReviewWorkflowsWorkflowStageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowStageEntityResponseCollection
  reviewWorkflowsWorkflows(filters: ReviewWorkflowsWorkflowFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [ReviewWorkflowsWorkflow]!
  reviewWorkflowsWorkflows_connection(filters: ReviewWorkflowsWorkflowFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): ReviewWorkflowsWorkflowEntityResponseCollection
  temoignage(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): Temoignage
  temoignages(filters: TemoignageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [Temoignage]!
  temoignages_connection(filters: TemoignageFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): TemoignageEntityResponseCollection
  uploadFile(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): UploadFile
  uploadFiles(filters: UploadFileFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UploadFile]!
  uploadFiles_connection(filters: UploadFileFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): UploadFileEntityResponseCollection
  usersPermissionsRole(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): UsersPermissionsRole
  usersPermissionsRoles(filters: UsersPermissionsRoleFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UsersPermissionsRole]!
  usersPermissionsRoles_connection(filters: UsersPermissionsRoleFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): UsersPermissionsRoleEntityResponseCollection
  usersPermissionsUser(documentId: ID!, hasPublishedVersion: Boolean, publicationFilter: PublicationFilter, status: PublicationStatus = PUBLISHED): UsersPermissionsUser
  usersPermissionsUsers(filters: UsersPermissionsUserFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): [UsersPermissionsUser]!
  usersPermissionsUsers_connection(filters: UsersPermissionsUserFiltersInput, hasPublishedVersion: Boolean, pagination: PaginationArg = {  }, publicationFilter: PublicationFilter, sort: [String] = [], status: PublicationStatus = PUBLISHED): UsersPermissionsUserEntityResponseCollection
}

type ReviewWorkflowsWorkflow {
  contentTypes: JSON!
  createdAt: DateTime
  documentId: ID!
  name: String!
  publishedAt: DateTime
  stageRequiredToPublish: ReviewWorkflowsWorkflowStage
  stages(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [ReviewWorkflowsWorkflowStage]!
  stages_connection(filters: ReviewWorkflowsWorkflowStageFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): ReviewWorkflowsWorkflowStageRelationResponseCollection
  updatedAt: DateTime
}

type ReviewWorkflowsWorkflowEntityResponseCollection {
  nodes: [ReviewWorkflowsWorkflow!]!
  pageInfo: Pagination!
}

input ReviewWorkflowsWorkflowFiltersInput {
  and: [ReviewWorkflowsWorkflowFiltersInput]
  contentTypes: JSONFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  name: StringFilterInput
  not: ReviewWorkflowsWorkflowFiltersInput
  or: [ReviewWorkflowsWorkflowFiltersInput]
  publishedAt: DateTimeFilterInput
  stageRequiredToPublish: ReviewWorkflowsWorkflowStageFiltersInput
  stages: ReviewWorkflowsWorkflowStageFiltersInput
  updatedAt: DateTimeFilterInput
}

input ReviewWorkflowsWorkflowInput {
  contentTypes: JSON
  locale: String
  name: String
  publishedAt: DateTime
  stageRequiredToPublish: ID
  stages: [ID]
}

type ReviewWorkflowsWorkflowStage {
  color: String
  createdAt: DateTime
  documentId: ID!
  name: String
  publishedAt: DateTime
  updatedAt: DateTime
  workflow: ReviewWorkflowsWorkflow
}

type ReviewWorkflowsWorkflowStageEntityResponseCollection {
  nodes: [ReviewWorkflowsWorkflowStage!]!
  pageInfo: Pagination!
}

input ReviewWorkflowsWorkflowStageFiltersInput {
  and: [ReviewWorkflowsWorkflowStageFiltersInput]
  color: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  name: StringFilterInput
  not: ReviewWorkflowsWorkflowStageFiltersInput
  or: [ReviewWorkflowsWorkflowStageFiltersInput]
  publishedAt: DateTimeFilterInput
  updatedAt: DateTimeFilterInput
  workflow: ReviewWorkflowsWorkflowFiltersInput
}

input ReviewWorkflowsWorkflowStageInput {
  color: String
  locale: String
  name: String
  publishedAt: DateTime
  workflow: ID
}

type ReviewWorkflowsWorkflowStageRelationResponseCollection {
  nodes: [ReviewWorkflowsWorkflowStage!]!
}

input StringFilterInput {
  and: [String]
  between: [String]
  contains: String
  containsi: String
  endsWith: String
  eq: String
  eqi: String
  gt: String
  gte: String
  in: [String]
  lt: String
  lte: String
  ne: String
  nei: String
  not: StringFilterInput
  notContains: String
  notContainsi: String
  notIn: [String]
  notNull: Boolean
  null: Boolean
  or: [String]
  startsWith: String
}

type Temoignage {
  avatar: UploadFile
  createdAt: DateTime
  documentId: ID!
  event: Event
  person: String!
  programme: Programme
  publishedAt: DateTime
  summary: String!
  universe: ENUM_TEMOIGNAGE_UNIVERSE
  updatedAt: DateTime
}

type TemoignageEntityResponseCollection {
  nodes: [Temoignage!]!
  pageInfo: Pagination!
}

input TemoignageFiltersInput {
  and: [TemoignageFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  event: EventFiltersInput
  not: TemoignageFiltersInput
  or: [TemoignageFiltersInput]
  person: StringFilterInput
  programme: ProgrammeFiltersInput
  publishedAt: DateTimeFilterInput
  summary: StringFilterInput
  universe: StringFilterInput
  updatedAt: DateTimeFilterInput
}

input TemoignageInput {
  avatar: ID
  event: ID
  locale: String
  person: String
  programme: ID
  publishedAt: DateTime
  summary: String
  universe: ENUM_TEMOIGNAGE_UNIVERSE
}

type UploadFile {
  alternativeText: String
  caption: String
  createdAt: DateTime
  documentId: ID!
  ext: String
  focalPoint: JSON
  formats: JSON
  hash: String!
  height: Int
  mime: String!
  name: String!
  previewUrl: String
  provider: String!
  provider_metadata: JSON
  publishedAt: DateTime
  related: [GenericMorph]
  size: Float!
  updatedAt: DateTime
  url: String!
  width: Int
}

type UploadFileEntityResponseCollection {
  nodes: [UploadFile!]!
  pageInfo: Pagination!
}

input UploadFileFiltersInput {
  alternativeText: StringFilterInput
  and: [UploadFileFiltersInput]
  caption: StringFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  ext: StringFilterInput
  focalPoint: JSONFilterInput
  formats: JSONFilterInput
  hash: StringFilterInput
  height: IntFilterInput
  mime: StringFilterInput
  name: StringFilterInput
  not: UploadFileFiltersInput
  or: [UploadFileFiltersInput]
  previewUrl: StringFilterInput
  provider: StringFilterInput
  provider_metadata: JSONFilterInput
  publishedAt: DateTimeFilterInput
  size: FloatFilterInput
  updatedAt: DateTimeFilterInput
  url: StringFilterInput
  width: IntFilterInput
}

type UsersPermissionsCreateRolePayload {
  ok: Boolean!
}

type UsersPermissionsDeleteRolePayload {
  ok: Boolean!
}

input UsersPermissionsLoginInput {
  identifier: String!
  password: String!
  provider: String! = "local"
}

type UsersPermissionsLoginPayload {
  jwt: String
  user: UsersPermissionsMe!
}

type UsersPermissionsMe {
  blocked: Boolean
  confirmed: Boolean
  documentId: ID!
  email: String
  id: ID!
  role: UsersPermissionsMeRole
  username: String!
}

type UsersPermissionsMeRole {
  description: String
  id: ID!
  name: String!
  type: String
}

type UsersPermissionsPasswordPayload {
  ok: Boolean!
}

type UsersPermissionsPermission {
  action: String!
  createdAt: DateTime
  documentId: ID!
  publishedAt: DateTime
  role: UsersPermissionsRole
  updatedAt: DateTime
}

input UsersPermissionsPermissionFiltersInput {
  action: StringFilterInput
  and: [UsersPermissionsPermissionFiltersInput]
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  not: UsersPermissionsPermissionFiltersInput
  or: [UsersPermissionsPermissionFiltersInput]
  publishedAt: DateTimeFilterInput
  role: UsersPermissionsRoleFiltersInput
  updatedAt: DateTimeFilterInput
}

type UsersPermissionsPermissionRelationResponseCollection {
  nodes: [UsersPermissionsPermission!]!
}

input UsersPermissionsRegisterInput {
  email: String!
  password: String!
  username: String!
}

type UsersPermissionsRole {
  createdAt: DateTime
  description: String
  documentId: ID!
  name: String!
  permissions(filters: UsersPermissionsPermissionFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [UsersPermissionsPermission]!
  permissions_connection(filters: UsersPermissionsPermissionFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): UsersPermissionsPermissionRelationResponseCollection
  publishedAt: DateTime
  type: String
  updatedAt: DateTime
  users(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): [UsersPermissionsUser]!
  users_connection(filters: UsersPermissionsUserFiltersInput, pagination: PaginationArg = {  }, sort: [String] = []): UsersPermissionsUserRelationResponseCollection
}

type UsersPermissionsRoleEntityResponseCollection {
  nodes: [UsersPermissionsRole!]!
  pageInfo: Pagination!
}

input UsersPermissionsRoleFiltersInput {
  and: [UsersPermissionsRoleFiltersInput]
  createdAt: DateTimeFilterInput
  description: StringFilterInput
  documentId: IDFilterInput
  name: StringFilterInput
  not: UsersPermissionsRoleFiltersInput
  or: [UsersPermissionsRoleFiltersInput]
  permissions: UsersPermissionsPermissionFiltersInput
  publishedAt: DateTimeFilterInput
  type: StringFilterInput
  updatedAt: DateTimeFilterInput
  users: UsersPermissionsUserFiltersInput
}

input UsersPermissionsRoleInput {
  description: String
  locale: String
  name: String
  permissions: [ID]
  publishedAt: DateTime
  type: String
  users: [ID]
}

type UsersPermissionsUpdateRolePayload {
  ok: Boolean!
}

type UsersPermissionsUser {
  blocked: Boolean
  confirmed: Boolean
  createdAt: DateTime
  documentId: ID!
  email: String!
  provider: String
  publishedAt: DateTime
  role: UsersPermissionsRole
  updatedAt: DateTime
  username: String!
}

type UsersPermissionsUserEntityResponse {
  data: UsersPermissionsUser
}

type UsersPermissionsUserEntityResponseCollection {
  nodes: [UsersPermissionsUser!]!
  pageInfo: Pagination!
}

input UsersPermissionsUserFiltersInput {
  and: [UsersPermissionsUserFiltersInput]
  blocked: BooleanFilterInput
  confirmed: BooleanFilterInput
  createdAt: DateTimeFilterInput
  documentId: IDFilterInput
  email: StringFilterInput
  not: UsersPermissionsUserFiltersInput
  or: [UsersPermissionsUserFiltersInput]
  provider: StringFilterInput
  publishedAt: DateTimeFilterInput
  role: UsersPermissionsRoleFiltersInput
  updatedAt: DateTimeFilterInput
  username: StringFilterInput
}

input UsersPermissionsUserInput {
  blocked: Boolean
  confirmationToken: String
  confirmed: Boolean
  email: String
  locale: String
  password: String
  provider: String
  publishedAt: DateTime
  resetPasswordToken: String
  role: ID
  username: String
}

type UsersPermissionsUserRelationResponseCollection {
  nodes: [UsersPermissionsUser!]!
}